In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

- df_1 : 첫번째 데이터 오류발생
- df_2 : 첫번째 데이터에 userid를 추가함
- df_3 : 리뷰 date를 추가
- df_4 : 전처리를 진행
- df_6 : 전처리 합치고 최종 df

In [3]:
#이걸 가져오면 밑에 전처리는 생략 
df = pd.read_csv('/content/drive/MyDrive/df_6_final.csv')
df.head()
df.shape

(12330, 10)

In [ ]:
df['가게'].unique()

array(['후라이드참잘하는집-서강대점', '청년치킨-서교점', '베이직프라이드치킨-신촌직영점', '지코바치킨-신촌점',
       '교촌치킨-신촌점', '순살만공격-마포신촌점', '푸라닭-신수점', '치킨플러스-성산점', '이나닭강정-신촌점',
       '맘스터치피자앤치킨-연대점', '지코바치킨-독립문점', '치킨플러스-서교점', 'BHC-신촌점',
       '골라먹는3가지맛디디치킨-연세대점', '굽네치킨&피자-서강점', '굽네치킨&피자-남가좌1호점', '치킨더홈-서울이대점',
       '굽네치킨&피자-이대역점', '맥시칸치킨-연희점', '오늘통닭-신촌점', '숯미남숯불치킨에미친남자',
       '수준이다른치킨-마포신촌점', '자담치킨-신촌점', '마깐마포깐풍기-신촌본점', '페리카나-이대점',
       '굽네치킨&피자-신촌점', '지코바치킨-홍대점', 'BHC-홍대초교점', '노랑통닭-아현점',
       '피자와치킨의러브레터-서대문점', '바른치킨-공덕파크자이점', '페리카나-합정동점', '지코바치킨-남가좌점',
       '롯데리아-홍대점', '컬투치킨-연남사랑점', '전국3대치킨오성통닭-마포신촌점', '쌀통에퐁닭', '네네치킨-서교점',
       '가마로강정-광흥창점', 'BHC-연희점', '멕시칸치킨-연남점', '골라먹는3가지맛디디치킨-아현점',
       '페리카나-홍익대점', '신미경홍대닭갈비3', '강정이기가막혀-연희점', 'BBQ-신촌점', '처갓집양념치킨-독립문점',
       '양념이맛있는순살킹-아현점', '호식이두마리치킨-명지대점', '신미불닭발-서울본점', '푸라닭-합정점',
       '티바두마리치킨-신수서강대점', 'BHC-공덕점', '호치킨-마포래미안푸르지오점', '치킨시대-명지대점'],
      dtype=object)

In [ ]:
#299개 혹은 99개씩 리뷰를 뽑아서 중복된 치킨집이 없는 것을 확인
# 198개 299 *2
df['가게'].value_counts()

후라이드참잘하는집-서강대점       299
치킨더홈-서울이대점           299
베이직프라이드치킨-신촌직영점      299
BHC-공덕점              299
지코바치킨-남가좌점           299
순살만공격-마포신촌점          299
푸라닭-신수점              299
치킨플러스-성산점            299
이나닭강정-신촌점            299
청년치킨-서교점             299
지코바치킨-독립문점           299
치킨플러스-서교점            299
BHC-신촌점              299
굽네치킨&피자-이대역점         299
굽네치킨&피자-서강점          299
굽네치킨&피자-남가좌1호점       299
BHC-홍대초교점            298
호식이두마리치킨-명지대점        297
골라먹는3가지맛디디치킨-아현점     295
컬투치킨-연남사랑점           295
맥시칸치킨-연희점            294
오늘통닭-신촌점             292
전국3대치킨오성통닭-마포신촌점     291
페리카나-홍익대점            288
골라먹는3가지맛디디치킨-연세대점    284
가마로강정-광흥창점           283
피자와치킨의러브레터-서대문점      281
쌀통에퐁닭                281
티바두마리치킨-신수서강대점       274
마깐마포깐풍기-신촌본점         274
처갓집양념치킨-독립문점         274
교촌치킨-신촌점             272
신미불닭발-서울본점           272
신미경홍대닭갈비3            272
페리카나-이대점             271
네네치킨-서교점             271
BHC-연희점              271
수준이다른치킨-마포신촌점        268
페리카나-합정동점            261
자담치킨-신촌점             260
지코바치킨-홍대점            257
굽네치킨&피자-신촌점          247
노랑통닭-아현점             217
맘스터치피자앤치킨-연대점         99
양념이맛있는순살킹-아현점         99
롯데리아-홍대점              99
바른치킨-공덕파크자이점          99
지코바치킨-신촌점             99
호치킨-마포래미안푸르지오점        99
치킨시대-명지대점             97
BBQ-신촌점               95
멕시칸치킨-연남점             95
강정이기가막혀-연희점           94
푸라닭-합정점               94
숯미남숯불치킨에미친남자          89
Name: 가게, dtype: int64

In [ ]:
df.iloc[20,:]

가게       후라이드참잘하는집-서강대점
맛                     5
양                     5
날짜           2023-02-09
주문               반마리（뼈）
사용자id                me
리뷰           맛있어요 ~~~~~
Name: 20, dtype: object

In [ ]:
df.iloc[10,:]

가게              후라이드참잘하는집-서강대점
맛                            5
양                            5
날짜                  2023-02-13
주문             눈꽃치즈치킨（무＋소스＋콜라）
사용자id                       ad
리뷰       잘먹었습니다. 지난번보다 더 맛있어요😊
Name: 10, dtype: object

## 사용자id 전처리하기

중복된 사용자가 있는지 확인하기
- 1번만 리뷰한 사용자들은 어떻게 할까?? 
- 사용자id에 이상한게 잇는 것도 있음

In [ ]:
#id는 2글자로 정했는데, 이게 아닌 경우가 있으니 확인해보자


user_id = []

for i,x in enumerate(df['사용자id'].tolist()):
  if len(x) > 2:
    user_id.append(i)

#user_id

In [ ]:
#user_id가 잘못된 것을 확인

df.loc[user_id,:]

,가게,맛,양,날짜,주문,사용자id,리뷰
431,청년치킨-서교점,5,5,2022-12-13,바삭매콤 후라이드,손님 2022년 12월 13일\n신고\n★★★★★ 맛 ★ 5 양 ★ 5 배달 ★ 5...,맛있어요 추천합니다
437,청년치킨-서교점,5,5,2022-12-09,\t,손님 2022년 12월 9일\n신고\n★★★★★ 맛 ★ 5 양 ★ 5 배달 ★ 5\n\t,\n바삭매콤 후라이드/1(뼈 or 순살 선택(순살))
443,청년치킨-서교점,5,5,2022-12-03,청년반반 세트（후라이드반＋,손님 2022년 12월 3일\n신고\n★★★★★ 맛 ★ 5 양 ★ 5 배달 ★ 5\...,빠르다고는 했는데 이 정도로 빠를줄은 몰랐네요 ㅎㅎ 후라이드도 딱 깔끔한 맛이여서 ...
498,청년치킨-서교점,5,5,2022-11-01,바삭매콤 후라이드,손님 2022년 11월 1일\n신고\n★★★★★ 맛 ★ 5 양 ★ 5 배달 ★ 5\...,배달도 빨리 오고 맛있었습니다
518,청년치킨-서교점,5,5,2022-10-15,바삭매콤 후라이드,손님 2022년 10월 15일\n신고\n★★★★★ 맛 ★ 5 양 ★ 5 배달 ★ 5...,맛있게 잘먹었습니다
...,...,...,...,...,...,...,...
12758,티바두마리치킨-신수서강대점,5,5,2022-04-16,어쩔만두세트1（뼈）두마리치킨,손님 2022년 4월 16일\n신고\n★★★★★ 맛 ★ 5 양 ★ 5 배달 ★ 4\...,처음 시켜봤는데 생각보다 양도 많고 아주 맛나게 잘 먹었습니다. 앞으로도 시켜먹을것...
12790,티바두마리치킨-신수서강대점,5,5,2022-03-28,어쩔만두세트1（뼈）두마리치킨,손님 2022년 3월 28일\n신고\n★★★★★ 맛 ★ 5 양 ★ 5 배달 ★ 5\...,👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻
12844,티바두마리치킨-신수서강대점,5,5,2022-03-06,어쩔만두세트1（뼈）두마리치킨,손님 2022년 3월 6일\n신고\n★★★★★ 맛 ★ 5 양 ★ 5 배달 ★ 5\n...,진짜 맛있는조합이에요
12877,티바두마리치킨-신수서강대점,5,5,2022-02-17,（순살）두마리세트 （한마리＋한마리＋콜라）,손님 2022년 2월 17일\n신고\n★★★★★ 맛 ★ 5 양 ★ 5 배달 ★ 5\...,드디어 똥집튀김이 생겨서 너무 행복해요! 이번주문에는 사진을 찍어두지 않아서 저번에...
13354,치킨시대-명지대점,5,5,2022-02-06,원하는대로 삼총사（반／반／반）,손님 2022년 2월 6일\n신고\n★★★★★ 맛 ★ 5 양 ★ 5 배달 ★ 5\n...,"익스프레스등록업체라 그런지 예상시간보다 빨리왔고 크리스피,간장.마늘 이렇게 먹었는데..."

In [ ]:
df.shape

(13382, 7)

In [ ]:
#위의 데이터는 유저아이디가 없으니 삭제하자
#207개의 데이터 삭제

df = df.drop(index = user_id)
df.shape

(13175, 7)

In [ ]:
df['사용자id'].value_counts()

ch    236
le    187
sh    183
ki    173
su    163
     ...
vv      1
pg      1
mt      1
kf      1
0e      1
Name: 사용자id, Length: 815, dtype: int64

In [ ]:
df['사용자id'].nunique()

815

In [ ]:
#다시 실행했을때 없는 것을 확인

user_id = []

for i,x in enumerate(df['사용자id'].tolist()):
  if len(x) > 2:
    user_id.append(i)
user_id

[]

In [ ]:
#제일 주문이 많은 사용자id : ch***** ch123 ch11
#이 프로젝트의 보완할 점 :  사용자id를 앞에 2글자로 제한했는데 앞에 2글자가 같은 유저의 경우 같은 아이디로 취급될 수 있음


df[df['사용자id'] == 'ch']

,가게,맛,양,날짜,주문,사용자id,리뷰
14,후라이드참잘하는집-서강대점,5,5,2023-02-12,반마리（순살）,ch,저는 후기를 자주 하지 않는 편인데 그래서도 해야지 이렇게 생각하는 만큼 맛있고 무...
62,후라이드참잘하는집-서강대점,3,4,2023-01-14,반반치킨（후라이드반＋,ch,후라이드반마리가 네조각인데 조각크기가 넘 커요 맛은 무난해요
67,후라이드참잘하는집-서강대점,2,5,2023-01-13,순살반반치킨（후라이드반＋,ch,치킨은 이상한맛났는데…
84,후라이드참잘하는집-서강대점,4,5,2022-12-31,순살 후라이드,ch,양이 많고 맛있었어용 !!!
88,후라이드참잘하는집-서강대점,4,5,2022-12-30,반마리（순살）,ch,맛과 양이 좋습니다
...,...,...,...,...,...,...,...
13128,BHC-공덕점,5,4,2022-11-15,치퐁당 스틱,ch,감사합니다. 맛있게 잘 먹었습니다~.
13134,BHC-공덕점,5,4,2022-11-07,뿌링클 콤보,ch,집근처보다 여기가 훨씬 맛나고 좋습니다
13268,호치킨-마포래미안푸르지오점,5,5,2022-12-03,[시그니처]치슐랭,ch,호치킨 흥해라 !!
13274,호치킨-마포래미안푸르지오점,5,5,2022-12-02,간장치킨,ch,호치킨 간장 치킨만 5번 넘게 시켜 먹었네요!
13283,호치킨-마포래미안푸르지오점,5,5,2022-11-26,간장치킨,ch,믿고 먹는 호치킨 간장치킨입니다+

In [ ]:
#사용자 id는 결측값이 없음

df[df['사용자id'].isna()]

Empty DataFrame
Columns: [가게, 맛, 양, 날짜, 주문, 사용자id, 리뷰]
Index: []

## 가게 전처리하기
- 이부분은 이미 해서 df_4_전처리가 됨

In [ ]:
df['가게'].unique()

array(['후라이드참잘하는집-서강대점', '청년치킨-서교점', '베이직프라이드치킨-신촌직영점', '지코바치킨-신촌점',
       '교촌치킨-신촌점', '순살만공격-마포신촌점', '푸라닭-신수점', '치킨플러스-성산점', '이나닭강정-신촌점',
       '맘스터치피자앤치킨-연대점', '지코바치킨-독립문점', '치킨플러스-서교점', 'BHC-신촌점',
       '골라먹는3가지맛디디치킨-연세대점', '굽네치킨&피자-서강점', '굽네치킨&피자-남가좌1호점', '치킨더홈-서울이대점',
       '굽네치킨&피자-이대역점', '맥시칸치킨-연희점', '오늘통닭-신촌점', '숯미남숯불치킨에미친남자',
       '수준이다른치킨-마포신촌점', '자담치킨-신촌점', '마깐마포깐풍기-신촌본점', '페리카나-이대점',
       '굽네치킨&피자-신촌점', '지코바치킨-홍대점', 'BHC-홍대초교점', '노랑통닭-아현점',
       '피자와치킨의러브레터-서대문점', '바른치킨-공덕파크자이점', '페리카나-합정동점', '지코바치킨-남가좌점',
       '롯데리아-홍대점', '컬투치킨-연남사랑점', '전국3대치킨오성통닭-마포신촌점', '쌀통에퐁닭', '네네치킨-서교점',
       '가마로강정-광흥창점', 'BHC-연희점', '롯데리아-신촌로터리점', '멕시칸치킨-연남점',
       '골라먹는3가지맛디디치킨-아현점', '페리카나-홍익대점', '파스타입니다-마포점', '신미경홍대닭갈비3',
       '강정이기가막혀-연희점', 'BBQ-신촌점', '처갓집양념치킨-독립문점', '양념이맛있는순살킹-아현점',
       '호식이두마리치킨-명지대점', '정가네추억떡볶이', '신미불닭발-서울본점', '푸라닭-합정점',
       '티바두마리치킨-신수서강대점', 'BHC-공덕점', '델리인디아', '호치킨-마포래미안푸르지오점',
       '치킨시대-명지대점'], dtype=object)

In [ ]:
#치킨집 아닌거 빼기
#킹케밥 킹케밥-홍대점 파스타어때-마포신촌본점 파스타입니다-마포점
#계산해보니 600개정도의 치킨집이 아닌 곳이 있어서 얘네는 제외시키자

temp = df.query('(가게 == "정가네추억떡볶이") or (가게 == "델리인디아") or (가게 == "롯데리아-신촌로터리점") or (가게 == "파스타입니다-마포점") ')
temp['가게'].value_counts()

롯데리아-신촌로터리점    299
파스타입니다-마포점     299
정가네추억떡볶이       299
델리인디아           99
Name: 가게, dtype: int64

In [ ]:
#인덱스를 확인 한 후에 제거
#새로운 df_1을 만듬

non_chicken = temp.index
df_1 = df.drop(index = non_chicken)

In [ ]:
#제대로 제거 되었나 확인

df_1.query('(가게 == "정가네추억떡볶이") or (가게 == "델리인디아") or (가게 == "롯데리아-신촌로터리점") or (가게 == "파스타입니다-마포점") ')

Empty DataFrame
Columns: [가게, 맛, 양, 날짜, 주문, 사용자id, 리뷰]
Index: []

In [ ]:
df_1['가게'].nunique()

55

In [ ]:
df_1.shape

(15041, 7)

데이터 수집 과정에서 커서를 아래로 내리다 중복해서 수집하는 경우가 있음;;
- 조사자 미숙;;
- 원래는 한 식당당 299개 혹은 99개의 리뷰가 들어가야함

In [ ]:
#오늘 통닭이 3번, BHC-공덕점가 2번, 푸라닭-합정점이 2번 들어감
#오늘 통닭의 리뷰를 2개 제거, BHC-공덕점가 1번, 푸라닭-합정점이 1번 제거 필요
df_1['가게'].value_counts()

오늘통닭-신촌점             897
BHC-공덕점              598
후라이드참잘하는집-서강대점       299
쌀통에퐁닭                299
지코바치킨-홍대점            299
청년치킨-서교점             299
노랑통닭-아현점             299
피자와치킨의러브레터-서대문점      299
페리카나-합정동점            299
지코바치킨-남가좌점           299
컬투치킨-연남사랑점           299
전국3대치킨오성통닭-마포신촌점     299
네네치킨-서교점             299
페리카나-이대점             299
가마로강정-광흥창점           299
BHC-연희점              299
골라먹는3가지맛디디치킨-아현점     299
페리카나-홍익대점            299
신미경홍대닭갈비3            299
처갓집양념치킨-독립문점         299
호식이두마리치킨-명지대점        299
신미불닭발-서울본점           299
티바두마리치킨-신수서강대점       299
굽네치킨&피자-신촌점          299
BHC-홍대초교점            299
마깐마포깐풍기-신촌본점         299
굽네치킨&피자-서강점          299
순살만공격-마포신촌점          299
교촌치킨-신촌점             299
치킨플러스-성산점            299
이나닭강정-신촌점            299
자담치킨-신촌점             299
지코바치킨-독립문점           299
치킨플러스-서교점            299
BHC-신촌점              299
골라먹는3가지맛디디치킨-연세대점    299
굽네치킨&피자-남가좌1호점       299
치킨더홈-서울이대점           299
굽네치킨&피자-이대역점         299
베이직프라이드치킨-신촌직영점      299
맥시칸치킨-연희점            299
수준이다른치킨-마포신촌점        299
푸라닭-신수점              299
푸라닭-합정점              198
양념이맛있는순살킹-아현점         99
지코바치킨-신촌점             99
호치킨-마포래미안푸르지오점        99
멕시칸치킨-연남점             99
BBQ-신촌점               99
강정이기가막혀-연희점           99
맘스터치피자앤치킨-연대점         99
롯데리아-홍대점              99
바른치킨-공덕파크자이점          99
숯미남숯불치킨에미친남자          99
치킨시대-명지대점             99
Name: 가게, dtype: int64

In [ ]:
#중복 식당의 인덱스를 이용해서 제거하기

id_1 = list(df_1[df_1['가게']== '오늘통닭-신촌점'].index)
id_2 = list(df_1[df_1['가게']== 'BHC-공덕점'].index)
id_3 = list(df_1[df_1['가게']== '푸라닭-합정점'].index)

for i in range(99):
  del id_3[i]

for i in range(299):
  del id_2[i]

for i in range(299):
  del id_1[i]

In [ ]:
# 중복 식당 제거

# df_2 = df_1.drop(index = id_1 )
# df_2 = df_2.drop(index = id_2 )
# df_2 = df_2.drop(index = id_3 )

In [ ]:
# 확인해보니 중복된 식당이 없는 것을 확인
#df_2['가게']

In [ ]:
#생각보다 음식 주문이 종류가 많지 않음

df_2['주문'].nunique()

5875

In [ ]:
#생각보다 음식 주문이 종류가 많지 않음

df_2['사용자id'].nunique()

1042

In [ ]:
#가게도 결측치 없음

df[df['가게'].isna()]

Empty DataFrame
Columns: [가게, 맛, 양, 날짜, 주문, 사용자id, 리뷰]
Index: []

주문 전처리하기

In [ ]:
#주문 전처리하기
#뒤에 쓸데없는 것은 제거

temp_1 = df_2['주문']

In [ ]:
#for i in temp_1.

0                             ★ 5 배달 ★ 5\n핫간장치킨（무＋소스＋콜라）/1
1                                    ★ 5 배달 ★ 5\n순살 후라이드/1
2             ★ 5 배달 ★ 5\n반마리（순살）/1(반마리 메뉴 선택(후라이드),추가 선택(
3                   ★ 5 배달 ★ 5\n반마리（순살）/1(반마리 메뉴 선택(후라이드))
4                          ★ 5 배달 ★ 5\n핫토스치킨（뼈）（무＋소스＋콜라）/1
                               ...
16032      ★ 5 배달 ★ 5\n크리스피치킨/1(음료 선택(콜라 1.25L로 변경),추가 선택(
16033     ★ 5 배달 ★ 5\n원하는대로 삼총사（반／반／반）/1(치킨선택1(크리스피（선택1...
16034                 ★ 5 배달 ★ 5\n크리스피치킨/1(음료 선택(콜라500mL))
16035                                       ★ 5 배달 ★ 5\n\t
16036                      ★ 5 배달 ★ 5\n내맘대로 두마리세트/1(치킨선택1(
Name: 주문, Length: 14045, dtype: object

In [ ]:
li = []
k = []
for idx,x in enumerate(temp_1):
  try:
      a = x.split('\n')[1]
      li.append(idx)
  except:
      k.append(idx)

In [ ]:
temp_1.loc[1223]

' ★ 5'

In [ ]:
df_2.loc[k,:]

,가게,맛,양,날짜,주문,사용자id,리뷰
1222,교촌치킨-신촌점,5,5,2022년 6월 11일,★ 5 배달 ★ 5,al,맛있어오용 또 시킬게영
1223,교촌치킨-신촌점,5,5,2022년 6월 7일,★ 5,ek,맛나게 잘 먹었습니당~~~!!
1225,교촌치킨-신촌점,5,5,2022년 6월 7일,★ 5 배달 ★ 5,cs,치킨 담아 주시는거 보고 정말 정성을 느꼈습니다. 떠 새벽 1시에 요기요 앱 점검 ...
1233,교촌치킨-신촌점,5,5,2022년 5월 24일,★ 5 배달 ★ 5,wh,.
1236,교촌치킨-신촌점,5,5,2022년 5월 20일,★ 5 배달 ★ 5,jy,가격이 올라서 슬프지만 맛있어ㅠㅠㅠ 배달 빠른편이어서 만족스러웠어요
...,...,...,...,...,...,...,...
13411,처갓집양념치킨-독립문점,1,1,2023년 1월 17일,★ 1 배달 ★ 2\n반반치킨/1(반반선택(허니올리고당야채,na,최악의 치킨 날씨 추워서 식은건 감안해요 닭고기인지 고무줄인지 구분도 안가고 배달하...
13415,처갓집양념치킨-독립문점,5,5,2023년 1월 16일,★ 5 배달 ★ 5\n순살 슈프림,cw,맛있게 먹었습니다.
13517,처갓집양념치킨-독립문점,5,5,2022년 11월 29일,★ 5 배달 ★ 5\n허니올리고당야채,de,치킨이 느무 맛있어서 마셨어요. 원래 치킨 한마리 다 못먹는데 여기껀 다먹어요. 양...
13988,호식이두마리치킨-명지대점,4,4,2022년 8월 16일,"★ 4 배달 ★ 5\n레몬크림탕슈（안심）＋한마리 세트/1(치킨분류 선택(순살),소...",ho,맛있게 잘먹었네여~~
13991,호식이두마리치킨-명지대점,4,5,2022년 8월 6일,"★ 5 배달 ★ 5\n한마리 ＋ 한마리/1(뼈 소스선택(후라이드),뼈 소스선택(",co,오늘은 맛이 좀 저번보다 못하네요. 약간 실망. 엄마가좋아하셔서 늘 시켰는데요

In [ ]:
k.remove(5526)

In [ ]:
k.remove(11630)
k.remove(11636)
k.remove(11638)
k.remove(11640)
k.remove(11654)
k.remove(11656)

In [ ]:
df_2 = df_2.drop(index = k)

In [ ]:
list(map(lambda x : x.split('\n')[1],df_2['주문']))

IndexError: ignored

In [ ]:
df_2.shape

(13693, 7)

In [ ]:
#기존에 리뷰중에 음식을 뭐 시켰는지 안 올린 리뷰가 있어서 
#예외처리로 음식정보가 없는 것의 인덱스를 찾기
#정보가 있는것은 음식이름을, 정보가 없는 리뷰는 '0'을 넣도록 해서 이후 '0'인 인덱스를 찾아서 해당 데이터 프레임에서 삭제하기 


ci = []
ans = []

for i in df_2.index.tolist():
  try:
    tt = df_2.loc[i]['주문']
    tts = tt.split('\n')[1]
    ans.append(tts)
  except:
    ci.append(i)
    ans.append('0')

In [ ]:
df_2['주문'] = ans

In [ ]:
id_food = df_2.query('주문 == "0"').index
df_2 = df_2.drop(index = id_food)

In [ ]:
df_2.head()

,가게,맛,양,날짜,주문,사용자id,리뷰
0,후라이드참잘하는집-서강대점,5,5,2일 전,핫간장치킨（무＋소스＋콜라）/1,st,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...
1,후라이드참잘하는집-서강대점,5,5,3일 전,순살 후라이드/1,yh,맛있어요 너무 맛ㅇㅅ어옿
2,후라이드참잘하는집-서강대점,5,5,4일 전,"반마리（순살）/1(반마리 메뉴 선택(후라이드),추가 선택(",id,너무 맛있게 잘 먹렀어요. 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다.
3,후라이드참잘하는집-서강대점,5,5,5일 전,반마리（순살）/1(반마리 메뉴 선택(후라이드)),rl,굳굳굳 잘 먹었습니당
4,후라이드참잘하는집-서강대점,5,5,5일 전,핫토스치킨（뼈）（무＋소스＋콜라）/1,st,시즈닝 팍팍~넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요

In [ ]:
# 주문 전처리 
# 뒤에 ()에는 기타 옵션이 들어가 있으니 중요한 건 아니니 제거하자
# 결과 기존 uni 364에서 221로 범위를 좁힘


a=list(map(lambda x : x.split('/')[0],df_2['주문']))
df_2['주문'] = a

In [ ]:
df_2['주문'].nunique()

1242

In [ ]:
df_2['사용자id'].nunique()

1022

날짜 전처리 하기
- 1일전 , 2일전 이런거 바꾸자 현재 날짜로 
- 그리고 계산을 편하게 하기 위해서 int형으로 바꿔보자 20230302이렇게 하면 최근날짜순을 알 수 있다.

In [ ]:
df['날짜']

0                 2일 전
1                 3일 전
2                 4일 전
3                 5일 전
4                 5일 전
             ...
16032    2021년 12월 22일
16033    2021년 12월 18일
16034    2021년 12월 16일
16035    2021년 12월 16일
16036    2021년 12월 12일
Name: 날짜, Length: 16037, dtype: object

In [ ]:
import re
kt=df_2.loc[16036]['날짜']
kt = kt.replace('년','')

kt = kt.replace('월','')

kt = kt.replace('일','')
kt = kt.replace(' ','')

int(kt)

20211212

In [ ]:
df_2.shape

(13382, 7)

In [ ]:
# 4시간 전은   20230221
# 1일 전은     20230220
# 2일 전은     20230219
# 3일 전       20230218
# 4일 전       20230217
# 5일 전       20230216
# 6일 전       20230215
# 일주일 전    20230214
from datetime import datetime, timedelta

temp_date =[]
for i in df_2.index.tolist():
  aa = df_2.loc[i]['날짜']
  if aa == '4시간 전' or aa == '3시간 전' or aa == '7시간 전' or aa == '9시간 전' or aa == '18시간 전' or aa == '22시간 전' or aa == '23시간 전' or aa == '2시간 전' or aa == '8시간 전' or aa == '21시간 전' or aa == '20시간 전' or aa == '6시간 전' or aa == '14시간 전':
    temp_date.append(datetime(2023,2,21))
  elif aa == '1일 전' or aa =='어제' :
    temp_date.append(datetime(2023,2,20))
  elif aa == '2일 전' :
    temp_date.append(datetime(2023,2,19))
  elif aa == '3일 전' :
    temp_date.append(datetime(2023,2,18))
  elif aa == '4일 전' :
    temp_date.append(datetime(2023,2,17))
  elif aa == '5일 전' :
    temp_date.append(datetime(2023,2,16))
  elif aa == '6일 전' :
    temp_date.append(datetime(2023,2,15))
  elif aa == '일주일 전' :
    temp_date.append(datetime(2023,2,14))
  else:
    # aa = aa.replace('년','')

    # aa = aa.replace('월','')

    # aa = aa.replace('일','')
    # aa = aa.replace(' ','')

    temp_date.append(datetime.strptime(aa, "%Y년 %m월 %d일"))

In [ ]:
datetime(2023,2,20)

datetime.datetime(2023, 2, 20, 0, 0)

In [ ]:
dt = df_2.loc[1555]['날짜']
datetime.strptime(dt, "%Y년 %m월 %d일")
#datetime.strptime(dt, "%년 %월 %일")

datetime.datetime(2022, 7, 31, 0, 0)

In [ ]:
df_3 = df_2.copy()

In [ ]:
df_3['날짜'] = temp_date

In [ ]:
df_2.head()

,가게,맛,양,날짜,주문,사용자id,리뷰
0,후라이드참잘하는집-서강대점,5,5,2일 전,핫간장치킨（무＋소스＋콜라）,st,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...
1,후라이드참잘하는집-서강대점,5,5,3일 전,순살 후라이드,yh,맛있어요 너무 맛ㅇㅅ어옿
2,후라이드참잘하는집-서강대점,5,5,4일 전,반마리（순살）,id,너무 맛있게 잘 먹렀어요. 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다.
3,후라이드참잘하는집-서강대점,5,5,5일 전,반마리（순살）,rl,굳굳굳 잘 먹었습니당
4,후라이드참잘하는집-서강대점,5,5,5일 전,핫토스치킨（뼈）（무＋소스＋콜라）,st,시즈닝 팍팍~넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요

In [ ]:
df_3.head()

,가게,맛,양,날짜,주문,사용자id,리뷰
0,후라이드참잘하는집-서강대점,5,5,2023-02-19,핫간장치킨（무＋소스＋콜라）,st,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...
1,후라이드참잘하는집-서강대점,5,5,2023-02-18,순살 후라이드,yh,맛있어요 너무 맛ㅇㅅ어옿
2,후라이드참잘하는집-서강대점,5,5,2023-02-17,반마리（순살）,id,너무 맛있게 잘 먹렀어요. 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다.
3,후라이드참잘하는집-서강대점,5,5,2023-02-16,반마리（순살）,rl,굳굳굳 잘 먹었습니당
4,후라이드참잘하는집-서강대점,5,5,2023-02-16,핫토스치킨（뼈）（무＋소스＋콜라）,st,시즈닝 팍팍~넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요

In [ ]:
#인덱스 초기화
df_3.reset_index(drop = True,inplace = True)

In [ ]:
df_3.head()

,가게,맛,양,날짜,주문,사용자id,리뷰
0,후라이드참잘하는집-서강대점,5,5,2023-02-19,핫간장치킨（무＋소스＋콜라）,st,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...
1,후라이드참잘하는집-서강대점,5,5,2023-02-18,순살 후라이드,yh,맛있어요 너무 맛ㅇㅅ어옿
2,후라이드참잘하는집-서강대점,5,5,2023-02-17,반마리（순살）,id,너무 맛있게 잘 먹렀어요. 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다.
3,후라이드참잘하는집-서강대점,5,5,2023-02-16,반마리（순살）,rl,굳굳굳 잘 먹었습니당
4,후라이드참잘하는집-서강대점,5,5,2023-02-16,핫토스치킨（뼈）（무＋소스＋콜라）,st,시즈닝 팍팍~넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요

In [ ]:
df_3.to_csv('df_4_plus_전처리.csv',index = False,encoding="utf-8-sig")

In [ ]:
df_3.loc[263]

가게            후라이드참잘하는집-서강대점
맛                          5
양                          5
날짜       2022-08-15 00:00:00
주문             후라이드（무＋소스＋콜라）
사용자id                     ui
리뷰               후라이드는 후참잘!!
Name: 263, dtype: object

In [ ]:
#날짜도 결측치 없음

df[df['날짜'].isna()]

Empty DataFrame
Columns: [가게, 맛, 양, 날짜, 주문, 사용자id, 리뷰]
Index: []

## 맛과 양의 전처리
- 확인 결과 value_count를 해도 그냥 숫자만 나옴 이상없음

In [ ]:
df['맛'].value_counts()

5    12306
4      556
3      160
1       98
2       55
Name: 맛, dtype: int64

In [ ]:
df['양'].value_counts()

5    12337
4      575
3      159
1       62
2       42
Name: 양, dtype: int64

In [ ]:
df[df['맛'].isna()]

Empty DataFrame
Columns: [가게, 맛, 양, 날짜, 주문, 사용자id, 리뷰]
Index: []

In [ ]:
df[df['양'].isna()]

Empty DataFrame
Columns: [가게, 맛, 양, 날짜, 주문, 사용자id, 리뷰]
Index: []

리뷰 전처리하기
- 이모티콘등은 삭제하기
- 은어나 인터넷 용어는 어떻게 해야 할지

In [ ]:
# 인덱스 초기화

df_1 =df.reset_index(drop = True)

In [ ]:
review_list = []

for i,x in enumerate(df_1['리뷰'].tolist()):
  
  try:
    if len(x) <= 4:
      review_list.append(i)
  except:
    review_list.append(i)
review_list

[91,
 332,
 501,
 656,
 755,
 812,
 913,
 1109,
 1581,
 2192,
 2561,
 2855,
 2885,
 2945,
 3195,
 3216,
 3314,
 3455,
 3890,
 4022,
 4520,
 5001,
 5046,
 5086,
 5489,
 6044,
 6370,
 6491,
 6497,
 6595,
 6705,
 6713,
 7124,
 7140,
 7547,
 7619,
 7866,
 8009,
 8066,
 8309,
 8454,
 8493,
 9347,
 9653,
 9845,
 10737,
 10911,
 10956,
 11012,
 11373,
 11377,
 12251,
 12484]

In [ ]:
#얘네는 어떻게 하지??
#리뷰가 .이나 nan은 삭제하면 될 것같고, 한글자 리뷰나 이모티콘리뷰는 아래에서 라이브러리를 쓰면 삭제될듯????
#53개이니 그냥 삭제하자

df_1.loc[review_list,:]

,가게,맛,양,날짜,주문,사용자id,리뷰
91,후라이드참잘하는집-서강대점,5,5,2022-12-28,후라이드（무＋소스＋콜라）,ru,감동
332,청년치킨-서교점,5,5,2023-02-07,NaN,yg,.
501,청년치킨-서교점,5,5,2022-10-23,바삭매콤 후라이드,94,good
656,베이직프라이드치킨-신촌직영점,5,5,2023-01-25,간장마고치킨 [이것은 요리입니다],zx,굿
755,베이직프라이드치킨-신촌직영점,5,5,2022-12-08,파닭파닭,ru,역시!
812,베이직프라이드치킨-신촌직영점,5,5,2022-11-25,더바삭치킨 [바삭담백사장추천],ru,🤗!
913,지코바치킨-신촌점,5,5,2023-02-16,순살,sa,존맛.
1109,교촌치킨-신촌점,5,5,2022-09-24,교촌레드윙,ku,.
1581,푸라닭-신수점,5,5,2023-01-15,콘소메이징,dl,굿
2192,이나닭강정-신촌점,5,5,2023-01-25,간장맛1박스,zx,굿
2561,지코바치킨-독립문점,5,5,2023-02-11,순살,se,맛있어요
2855,치킨플러스-서교점,5,5,2023-02-19,두마리세트,sa,👍👍👍
2885,치킨플러스-서교점,5,5,2023-01-25,킹부각치킨（with지도표성경김） ＋ 밀크치즈볼（5개）,zx,굿굿
2945,치킨플러스-서교점,5,5,2022-12-17,No.1 포테이토닥토닭,zx,잘먹음용
3195,BHC-신촌점,5,5,2023-01-13,후라이드（반）＋뿌링치즈볼,re,좋아모
3216,BHC-신촌점,5,5,2022-12-30,뿌링클 콤보,sk,맛있어요
3314,BHC-신촌점,3,3,2022-11-06,후라이드 반／,bl,잘
3455,골라먹는3가지맛디디치킨-연세대점,5,5,2023-01-13,2마리 3가지맛세트 오리지널,di,존맛
3890,굽네치킨&피자-서강점,5,5,2022-12-06,불금치킨,hf,굳
4022,굽네치킨&피자-남가좌1호점,5,5,2023-02-20,（New）남해마늘바사삭,di,맛나요
4520,치킨더홈-서울이대점,5,5,2022-10-07,NaN,11,말모
5001,맥시칸치킨-연희점,5,5,2022-03-25,닭강정,ad,맛있어요
5046,맥시칸치킨-연희점,5,5,2022-01-10,닭강정,z1,😋😋😋
5086,맥시칸치킨-연희점,5,5,2021-10-23,닭강정,56,맛있어요
5489,수준이다른치킨-마포신촌점,5,5,2022-09-23,（후라이드）빠삭킹 마늘간장 반 반 （추천메뉴）,ka,맛있어요
6044,마깐마포깐풍기-신촌본점,5,5,2022-02-28,수제똥집튀김 C세트（깐풍기大＋똥집＋무＋샐러드＋콜라 500mL）,pi,맛있어요
6370,페리카나-이대점,5,5,2022-04-01,NaN,da,굳
6491,굽네치킨&피자-신촌점,5,5,2023-02-18,고추바사삭,lc,예아
6497,굽네치킨&피자-신촌점,5,5,2023-01-26,오리지널,re,맛있어요
6595,굽네치킨&피자-신촌점,5,5,2022-10-06,오리지널,jo,맛있어요
6705,굽네치킨&피자-신촌점,5,5,2022-06-22,（New）오븐바사삭,rr,good
6713,굽네치킨&피자-신촌점,5,5,2022-06-14,（New）오븐바사삭,rr,good
7124,BHC-홍대초교점,5,5,2023-01-26,맛초킹,al,맛있어요
7140,BHC-홍대초교점,5,5,2023-01-20,하바네로 포테킹 후라이드,sl,좋아요
7547,피자와치킨의러브레터-서대문점,5,5,2022-10-31,후라이드치킨＋피자선택（M）＋펩시콜라500mL,th,푸짐해요
7619,피자와치킨의러브레터-서대문점,5,5,2022-06-11,\t,ha,NaN
7866,바른치킨-공덕파크자이점,5,5,2022-11-11,현미바사삭,el,맛있어요
8009,페리카나-합정동점,5,5,2022-07-24,후라이드치킨,wh,👍.
8066,페리카나-합정동점,5,5,2022-05-24,\t,tl,NaN
8309,지코바치킨-남가좌점,5,5,2022-09-25,순살,di,맛있어요
8454,롯데리아-홍대점,5,5,2023-01-24,불고기버거세트,yg,.
8493,롯데리아-홍대점,5,5,2022-11-17,모짜렐라인더 버거-베이컨 세트,a0,👍.
9347,네네치킨-서교점,5,5,2023-02-16,순살오리엔탈파닭,ka,맛있어여
9653,가마로강정-광흥창점,5,3,2022-06-27,더블（원하는 강정 2가지）,gi,.
9845,가마로강정-광흥창점,5,5,2020-08-23,반반（매콤강정＋달콤강정）,db,맛있어요
10737,페리카나-홍익대점,5,5,2022-10-06,반반치킨,ru,가성비짱
10911,페리카나-홍익대점,5,5,2022-06-23,순살반반,zx,네
10956,신미경홍대닭갈비3,5,5,2023-02-19,신미경숯불반반메뉴,sa,ㅣ
11012,신미경홍대닭갈비3,5,5,2023-02-02,닭갈비（소）550g＋막국수,sh,맛잇네요
11373,BBQ-신촌점,5,5,2021-09-18,황금올리브（반반）,rr,good
11377,BBQ-신촌점,5,5,2021-09-16,황금올리브（반반）,km,맛있네용
12251,신미불닭발-서울본점,5,5,2022-05-06,무뼈닭발Set,dl,굿
12484,티바두마리치킨-신수서강대점,5,5,2022-08-11,[8500원혜택],sh,맛잇어용

In [ ]:
#위의 리뷰데이터는 삭제
df_1.drop(index = review_list,inplace = True)

In [ ]:
#인덱스 정렬
df_1 =df_1.reset_index(drop = True)

In [ ]:
#제대로 삭제됨

review_list = []

for i,x in enumerate(df_1['리뷰'].tolist()):
  
  try:
    if len(x) <= 4:
      review_list.append(i)
  except:
    review_list.append(i)

review_list

[]

위에서 보니 주문도 이상한게 있음
- 상식적으로 주문내역이 "치킨"이렇게 2글자일리는 없음 아까 3글자 반마리는 봄
- 따라서 3글자 이하는 다 찾아보자

In [ ]:
food_list = []

for i,x in enumerate(df_1['주문'].tolist()):
  
  try:
    if len(x) <= 4:
      food_list.append(i)
  except:
    food_list.append(i)

food_list

[13,
 40,
 59,
 64,
 101,
 103,
 122,
 172,
 200,
 207,
 222,
 233,
 235,
 260,
 264,
 272,
 278,
 305,
 307,
 314,
 350,
 355,
 368,
 370,
 372,
 379,
 385,
 402,
 412,
 417,
 423,
 425,
 437,
 476,
 481,
 502,
 523,
 524,
 560,
 568,
 582,
 615,
 624,
 633,
 673,
 686,
 693,
 722,
 723,
 739,
 751,
 762,
 786,
 798,
 803,
 832,
 845,
 866,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 898,
 899,
 900,
 901,
 902,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 914,
 915,
 916,
 917,
 918,
 919,
 921,
 922,
 923,
 924,
 925,
 927,
 928,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 951,
 952,
 953,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 985,
 986,
 987,
 988,
 991,
 992,
 999,
 1003,
 1006,
 1007,
 1009,
 1010,
 1012,
 1013,
 1014,
 1016,
 1017,
 1021,
 1022,
 1023,
 1026,
 1027,
 1028,
 1029,
 1032,
 1033,
 1036,
 1037,
 1038,
 1042,
 1043,
 1048,
 1049,
 1050,
 1052,
 1053,
 1055,
 1056,
 1057,
 1058,
 1059,
 1061,
 1074,
 1080,
 1082,
 1093,
 1100,
 1128,
 1129,
 1152,
 1159,
 1177,
 1208,
 1223,
 1272,
 1273,
 1323,
 1407,
 1429,
 1462,
 1569,
 1591,
 1618,
 1640,
 1672,
 1706,
 1709,
 1725,
 1728,
 1729,
 1737,
 1743,
 1761,
 1792,
 1801,
 1814,
 1819,
 1833,
 1841,
 1854,
 1878,
 1891,
 1899,
 1909,
 1912,
 1922,
 1924,
 1938,
 1944,
 1958,
 1959,
 1960,
 1964,
 1965,
 1970,
 1983,
 1985,
 1992,
 2005,
 2018,
 2019,
 2025,
 2028,
 2040,
 2044,
 2057,
 2059,
 2083,
 2092,
 2093,
 2110,
 2111,
 2114,
 2117,
 2118,
 2122,
 2127,
 2140,
 2141,
 2161,
 2189,
 2204,
 2206,
 2267,
 2274,
 2308,
 2314,
 2441,
 2449,
 2457,
 2459,
 2460,
 2462,
 2474,
 2485,
 2489,
 2499,
 2500,
 2506,
 2515,
 2526,
 2538,
 2539,
 2540,
 2541,
 2542,
 2543,
 2544,
 2546,
 2548,
 2549,
 2550,
 2551,
 2552,
 2553,
 2554,
 2555,
 2556,
 2557,
 2558,
 2559,
 2560,
 2561,
 2562,
 2564,
 2566,
 2567,
 2569,
 2570,
 2572,
 2573,
 2574,
 2575,
 2576,
 2577,
 2578,
 2579,
 2580,
 2581,
 2582,
 2583,
 2584,
 2585,
 2586,
 2587,
 2588,
 2589,
 2590,
 2591,
 2592,
 2593,
 2594,
 2595,
 2596,
 2597,
 2598,
 2599,
 2600,
 2602,
 2604,
 2605,
 2606,
 2607,
 2608,
 2609,
 2610,
 2611,
 2612,
 2613,
 2614,
 2615,
 2616,
 2617,
 2620,
 2621,
 2623,
 2625,
 2626,
 2628,
 2630,
 2631,
 2632,
 2633,
 2634,
 2635,
 2636,
 2637,
 2638,
 2639,
 2640,
 2641,
 2642,
 2643,
 2644,
 2645,
 2646,
 2647,
 2648,
 2649,
 2650,
 2651,
 2652,
 2653,
 2654,
 2655,
 2656,
 2658,
 2660,
 2661,
 2662,
 2664,
 2665,
 2666,
 2667,
 2668,
 2669,
 2670,
 2671,
 2672,
 2673,
 2674,
 2675,
 2676,
 2677,
 2678,
 2679,
 2680,
 2681,
 2682,
 2683,
 2685,
 2686,
 2687,
 2688,
 2689,
 2690,
 2691,
 2692,
 2693,
 2694,
 2695,
 2696,
 2697,
 2698,
 2699,
 2700,
 2701,
 2702,
 2703,
 2704,
 2705,
 2706,
 2707,
 2708,
 2709,
 2710,
 2712,
 2713,
 2714,
 2715,
 2716,
 2717,
 2718,
 2719,
 2720,
 2721,
 2722,
 2723,
 2724,
 2725,
 2726,
 2727,
 2728,
 2729,
 2730,
 2732,
 2733,
 2734,
 2735,
 2736,
 2737,
 2738,
 2739,
 2740,
 2741,
 2742,
 2743,
 2744,
 2745,
 2746,
 2748,
 2749,
 2750,
 2751,
 2752,
 2754,
 2755,
 2756,
 2757,
 2758,
 2759,
 2760,
 2761,
 2762,
 2763,
 2764,
 2765,
 2766,
 2767,
 2768,
 2769,
 2770,
 2771,
 2772,
 2773,
 2774,
 2775,
 2776,
 2777,
 2778,
 2780,
 2781,
 2782,
 2783,
 2784,
 2785,
 2786,
 2787,
 2788,
 2789,
 2790,
 2791,
 2792,
 2793,
 2794,
 2795,
 2796,
 2797,
 2798,
 2799,
 2800,
 2801,
 2802,
 2803,
 2804,
 2805,
 2806,
 2807,
 2808,
 2809,
 2811,
 2812,
 2813,
 2814,
 2815,
 2816,
 2817,
 2818,
 2819,
 2820,
 2821,
 2822,
 2823,
 2824,
 2825,
 2826,
 2827,
 2828,
 2829,
 2830,
 2831,
 2832,
 2833,
 2834,
 2837,
 2843,
 2849,
 2867,
 2871,
 2878,
 2887,
 2892,
 2903,
 2905,
 2912,
 2919,
 2923,
 2931,
 2934,
 2939,
 2956,
 2974,
 2977,
 2978,
 2979,
 2981,
 2985,
 3004,
 3006,
 3020,
 3049,
 3052,
 3054,
 3065,
 3072,
 3073,
 3074,
 3090,
 3096,
 3097,
 3099,
 3101,
 3104,
 3109,
 3116,
 3119,
 3126,
 3128,
 3129,
 3132,
 3133,
 3136,
 3137,
 3138,
 3140,
 3142,
 3143,
 3145,
 3146,
 3147,
 3148,
 3153,
 3155,
 3160,
 3164,
 3165,
 3168,
 3175,
 3176,
 3185,
 3195,
 3196,
 3197,
 3198,
 3201,
 3202,
 3205,
 3206,
 3210,
 3215,
 3219,
 3225,
 3228,
 3232,
 3233,
 3236,
 3242,
 3249,
 3251,
 3253,
 3254,
 3258,
 3259,
 3260,
 3261,
 3262,
 3263,
 3265,
 3266,
 3268,
 3273,
 3277,
 3280,
 3281,
 3282,
 3285,
 3288,
 3293,
 3294,
 3295,
 3297,
 3298,
 3301,
 3303,
 3305,
 3308,
 3309,
 3315,
 3318,
 3330,
 3349,
 3354,
 3355,
 3356,
 3361,
 3364,
 3366,
 3367,
 3375,
 3376,
 3377,
 3378,
 3379,
 3383,
 3384,
 3385,
 3390,
 3395,
 3402,
 3407,
 3409,
 3411,
 3416,
 3421,
 3437,
 3446,
 3450,
 3475,
 3479,
 3494,
 3498,
 3506,
 3551,
 3567,
 3596,
 3622,
 3625,
 3633,
 3647,
 3662,
 3665,
 3669,
 3670,
 3673,
 3687,
 3701,
 3702,
 3703,
 3714,
 3715,
 3718,
 3719,
 3720,
 3722,
 3727,
 3728,
 3731,
 3737,
 3738,
 3742,
 3747,
 3749,
 3753,
 3758,
 3765,
 3766,
 3768,
 3769,
 3772,
 3776,
 3777,
 3780,
 3781,
 3785,
 3788,
 3806,
 3811,
 3817,
 3818,
 3819,
 3820,
 3827,
 3828,
 3831,
 3834,
 3835,
 3837,
 3838,
 3839,
 3843,
 3844,
 3845,
 3850,
 3851,
 3853,
 3855,
 3856,
 3859,
 3862,
 3863,
 3864,
 3866,
 3870,
 3873,
 3879,
 3880,
 3882,
 3886,
 3887,
 3891,
 3892,
 3894,
 3902,
 3908,
 3914,
 3917,
 3919,
 3922,
 3927,
 3932,
 3933,
 3937,
 3938,
 3939,
 3943,
 3945,
 3948,
 3951,
 3952,
 3953,
 3954,
 3956,
 3958,
 3959,
 3967,
 3974,
 3976,
 3978,
 3980,
 3988,
 3995,
 3996,
 4000,
 4008,
 4009,
 4010,
 4012,
 4014,
 4020,
 4023,
 4026,
 4027,
 4028,
 4031,
 4034,
 4038,
 4044,
 4045,
 4049,
 4053,
 4063,
 4065,
 4066,
 4067,
 4068,
 4069,
 4070,
 4073,
 4074,
 4075,
 4080,
 4081,
 4082,
 4086,
 4092,
 4094,
 4096,
 4097,
 4099,
 4102,
 4103,
 4114,
 4120,
 4123,
 4126,
 4128,
 4129,
 4138,
 4144,
 4151,
 4152,
 4156,
 4158,
 4162,
 4166,
 4168,
 4169,
 4172,
 4173,
 4174,
 4176,
 4177,
 4179,
 4181,
 4183,
 4184,
 4185,
 4188,
 4190,
 4191,
 4192,
 4198,
 4201,
 4202,
 4204,
 4205,
 4210,
 4214,
 4216,
 4217,
 4219,
 4224,
 4229,
 4231,
 4232,
 4235,
 4236,
 4240,
 4244,
 4245,
 4251,
 4257,
 4258,
 4259,
 4263,
 4279,
 4284,
 4286,
 4288,
 4289,
 4291,
 4293,
 4300,
 4308,
 4324,
 4337,
 4348,
 4356,
 4372,
 4381,
 4390,
 4396,
 4403,
 4410,
 4411,
 4413,
 4414,
 4415,
 4429,
 4437,
 4438,
 4439,
 4445,
 4457,
 4462,
 4465,
 4470,
 4471,
 4481,
 4486,
 4488,
 4500,
 4502,
 4508,
 4509,
 4512,
 4515,
 4527,
 4537,
 4547,
 4559,
 4561,
 4562,
 4570,
 4572,
 4587,
 4598,
 4600,
 4602,
 4610,
 4612,
 4617,
 4621,
 4623,
 4625,
 4626,
 4630,
 4635,
 4638,
 4643,
 4650,
 4652,
 4653,
 4655,
 4656,
 4658,
 4662,
 4663,
 4665,
 4670,
 4672,
 4675,
 4678,
 4680,
 4684,
 4689,
 4692,
 4693,
 4694,
 4700,
 4704,
 4706,
 4707,
 4708,
 4710,
 ...]

In [ ]:
#확인 해보니 그냥 순살이라는 메뉴가 있음

df_1.loc[food_list,:]

,가게,맛,양,날짜,주문,사용자id,리뷰
13,후라이드참잘하는집-서강대점,5,5,2023-02-12,순살,tj,소스 넉넉한거 보세요.. 진짜 존맛ㅠㅠ 어제 밤부터 먹고싶어서 벼르다가 일어나자마자...
40,후라이드참잘하는집-서강대점,5,5,2023-01-25,\t,kk,\n반반치킨（후라이드반＋양념반）/1
59,후라이드참잘하는집-서강대점,5,5,2023-01-15,NaN,eh,"서강대점 평점이 4.8? 이건 못참지~ 5점으로 혼내드립니다~ 최고의 바삭함, 안에..."
64,후라이드참잘하는집-서강대점,5,5,2023-01-13,순살,ge,가성비 갓의 순살 양념치킨! 2번째 먹는중
101,후라이드참잘하는집-서강대점,5,5,2022-12-16,\t,le,"\n순살 후라이드/1,반반치킨（양념반＋간장반）/1(콜라1.25L로변경(콜라1.25L..."
...,...,...,...,...,...,...,...
13109,치킨시대-명지대점,5,5,2022-01-05,\t,iy,"\n원하는대로 삼총사（반／반／반）/1(치킨선택1(간장치킨（선택1）),안심순살변경추가..."
13111,치킨시대-명지대점,5,5,2022-01-03,NaN,ki,빠른 배달 좋네요 치킨도 맛있구요 치킨무 2개 인데 1개만 왔어요 ㅋㅋ 다음에도 주...
13113,치킨시대-명지대점,5,5,2022-01-02,NaN,ng,너무너무 맛나요 진짜 치킨이 실~ 하고 양념도 너무 맛있어요 후라이드 육즙이 살아 ...
13116,치킨시대-명지대점,5,5,2021-12-23,NaN,hy,처음시켜보았는데 맛있네요 치즈볼도 정말 맛있었어요 하트야채도 감동이에요
13120,치킨시대-명지대점,5,5,2021-12-16,\t,sn,"\n크리스피치킨/1(음료 선택(콜라500mL),추가 선택(양념소스 추가,간장소스 추..."

In [ ]:
'''
1. 순살은 아래에서 보았듯이 지코바의 메뉴로 800개의 리뷰가 있으니 냅두자
2. \t는 삭제
3. 닭강정이나 반반치킨등 리뷰건수가 50개가 넘는 것은 남기고 나머지는 카디널리티만 높이니 삭제???


'''


df_1.loc[food_list,:]['주문'].value_counts()

순살      844
\t      317
닭강정     191
반반치킨    185
오리지널    175
       ...
폭립        1
대새골드      1
반반파닭      1
페리윙       1
신선윙       1
Name: 주문, Length: 121, dtype: int64

In [ ]:
#삭제 해야 할것
# '\t' '뼈 '  '청' 'SET）' '4.순살'


df_1.loc[food_list,:]['주문'].value_counts().to_dict()

{'순살': 844,
 '\t': 317,
 '닭강정': 191,
 '반반치킨': 185,
 '오리지널': 175,
 '뿌링클': 144,
 '후라이드': 118,
 '참숯 ': 76,
 '맛초킹': 76,
 '뼈 ': 76,
 '반반（': 68,
 '볼케이노': 68,
 '골드킹': 63,
 '순살 ': 61,
 '갈비천왕': 39,
 '불금치킨': 36,
 '뼈 반반': 31,
 '슈프림': 29,
 '무뼈닭발': 28,
 '꼬들목': 27,
 '순살반반': 26,
 '치킨텐더': 26,
 '컬투치킨': 22,
 '허니콤보': 22,
 '로스핀': 20,
 '혼치킨': 16,
 '간장치킨': 16,
 '블랙마요': 16,
 '순살치킨': 15,
 '신미경': 15,
 '커리퀸': 14,
 '바삭클': 13,
 '불패치킨': 11,
 '파닭파닭': 11,
 '트리플팩': 11,
 '맘스': 10,
 '매운': 10,
 '윙봉': 10,
 '싸이순살': 8,
 '반반콤보': 8,
 '다리（': 8,
 '대새레드': 7,
 '막창': 7,
 '찐4피자': 7,
 '깐풍치킨': 7,
 '순살청': 7,
 '옛날치킨': 7,
 '핫쵸킹': 7,
 '교촌윙': 7,
 '청': 6,
 '대새블랙': 6,
 '새우버거': 6,
 '교촌콤보': 5,
 '쉑쉑': 5,
 '파닭치킨': 5,
 '맵소킹': 5,
 '통닭뱅이': 5,
 '마늘치킨': 4,
 '파닭': 4,
 '레고치킨': 4,
 '닭다리': 4,
 '불닭발': 4,
 '맵삭치킨': 4,
 '레드킹': 4,
 '크리미': 4,
 '다리': 4,
 'SET）': 4,
 '레드윙': 3,
 '순살매운': 3,
 '블랙악마': 3,
 '매운불': 3,
 '갈릭마왕': 3,
 '레드콤보': 3,
 '매달구': 3,
 '꿀잼치킨': 3,
 '순살파닭': 2,
 '킹': 2,
 '똥집볶음': 2,
 '빠텐더': 2,
 '파티팩': 2,
 'XO': 2,
 '마늘강정': 2,
 '불닭치킨': 2,
 '허니멜로': 2,
 '다리날개': 2,
 '간장반＋': 2,
 '바른': 2,
 '반반 A': 2,
 '반반스틱': 2,
 '페리윙 ': 2,
 '달콤': 1,
 '간장강정': 1,
 '대마치킨': 1,
 '순한맛': 1,
 '매운맛': 1,
 '튀김세트': 1,
 '반반윙': 1,
 '교촌스틱': 1,
 '페퍼로니': 1,
 '반반순살': 1,
 '꼼장어': 1,
 '쿠키무스': 1,
 '똥집튀김': 1,
 '매운강정': 1,
 '치즈스틱': 1,
 '강정치킨': 1,
 '폭탄감자': 1,
 '데리버거': 1,
 '4.순살': 1,
 '콤보순살': 1,
 '웨지감자': 1,
 '순살갈릭': 1,
 '갈릭치킨': 1,
 '네네볶이': 1,
 '닭날개': 1,
 '신선핀 ': 1,
 '폭립': 1,
 '대새골드': 1,
 '반반파닭': 1,
 '페리윙': 1,
 '신선윙 ': 1}

In [ ]:
#'\t' '뼈 '  '청' 'SET）' '4.순살'
#약 400개 이것도 삭제하자

df_1.query('(주문 == "\t") or (주문 == "뼈 ") or (주문 == "청") or (주문 == "4.순살")')

,가게,맛,양,날짜,주문,사용자id,리뷰
40,후라이드참잘하는집-서강대점,5,5,2023-01-25,\t,kk,\n반반치킨（후라이드반＋양념반）/1
101,후라이드참잘하는집-서강대점,5,5,2022-12-16,\t,le,"\n순살 후라이드/1,반반치킨（양념반＋간장반）/1(콜라1.25L로변경(콜라1.25L..."
103,후라이드참잘하는집-서강대점,5,5,2022-12-10,\t,ki,\n순살반반치킨（후라이드반＋양념반）/1(추가 선택(감자튀김))
122,후라이드참잘하는집-서강대점,5,5,2022-11-23,\t,eu,\n순살반반치킨 （후라이드반＋킹트리플반）/1(추가 선택(감자튀김))
235,후라이드참잘하는집-서강대점,5,5,2022-08-31,\t,ms,\n반반치킨（후라이드반＋양념반）/1
...,...,...,...,...,...,...,...
13090,치킨시대-명지대점,5,5,2022-02-14,\t,km,\n양념으로 반반/1(음료 선택(사이다500mL))
13093,치킨시대-명지대점,5,5,2022-02-09,\t,ng,"\n원하는대로 삼총사（반／반／반）/1(치킨선택1(크리스피（선택1）),치킨선택2(양념..."
13100,치킨시대-명지대점,5,5,2022-01-21,\t,tm,"\n원하는대로 삼총사（반／반／반）/1(치킨선택1(크리스피（선택1）),안심순살변경추가..."
13109,치킨시대-명지대점,5,5,2022-01-05,\t,iy,"\n원하는대로 삼총사（반／반／반）/1(치킨선택1(간장치킨（선택1）),안심순살변경추가..."
13120,치킨시대-명지대점,5,5,2021-12-16,\t,sn,"\n크리스피치킨/1(음료 선택(콜라500mL),추가 선택(양념소스 추가,간장소스 추..."

In [ ]:
food_error_idx = df_1.query('(주문 == "\t") or (주문 == "뼈 ") or (주문 == "청") or (주문 == "4.순살")').index

df_1 = df_1.drop(index = food_error_idx)

In [ ]:
#주문이 누락된 것도 삭제

df_1[df_1['주문'].isna()]

,가게,맛,양,날짜,주문,사용자id,리뷰
59,후라이드참잘하는집-서강대점,5,5,2023-01-15,NaN,eh,"서강대점 평점이 4.8? 이건 못참지~ 5점으로 혼내드립니다~ 최고의 바삭함, 안에..."
172,후라이드참잘하는집-서강대점,5,5,2022-09-29,NaN,hy,맛있게먹었습미당항상
207,후라이드참잘하는집-서강대점,5,5,2022-09-14,NaN,kj,맛있게 잘 먹었습니다
222,후라이드참잘하는집-서강대점,5,5,2022-09-05,NaN,st,후라이드도 맛있지만 양념도 맛있어요 양념은 후참에서만 주문함ㅋㅋ양념이 바닥에 넘천 ...
264,후라이드참잘하는집-서강대점,5,5,2022-08-14,NaN,se,숭배합니다 GOAT
...,...,...,...,...,...,...,...
13087,치킨시대-명지대점,5,5,2022-02-18,NaN,pk,닭이 엄청 크네요! 치킨 샐러드 치즈볼 다 맛있게 먹었어요~ 다음에도 여기서 시킬 ...
13102,치킨시대-명지대점,5,5,2022-01-17,NaN,br,야채랑 치킨이랑 전부 너무 맛있었어요 ㅠㅠㅠㅠ 익스프레스인데도 배달 시작하고 35분...
13111,치킨시대-명지대점,5,5,2022-01-03,NaN,ki,빠른 배달 좋네요 치킨도 맛있구요 치킨무 2개 인데 1개만 왔어요 ㅋㅋ 다음에도 주...
13113,치킨시대-명지대점,5,5,2022-01-02,NaN,ng,너무너무 맛나요 진짜 치킨이 실~ 하고 양념도 너무 맛있어요 후라이드 육즙이 살아 ...
13116,치킨시대-명지대점,5,5,2021-12-23,NaN,hy,처음시켜보았는데 맛있네요 치즈볼도 정말 맛있었어요 하트야채도 감동이에요

In [ ]:
#주문 결측치 삭제

food_na_idx = df_1[df_1['주문'].isna()].index
df_1= df_1.drop(index = food_na_idx)

In [ ]:
df_1[df_1['주문'].isna()]

Empty DataFrame
Columns: [가게, 맛, 양, 날짜, 주문, 사용자id, 리뷰]
Index: []

리뷰 전처리하기
- 이모티콘이나 !등등 삭제하기

In [ ]:
df_1 =df_1.reset_index(drop = True)

In [ ]:
df_1.shape

(12330, 7)

In [ ]:
df.shape

(13175, 7)

In [ ]:
pip install krwordrank

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting krwordrank
  Downloading krwordrank-1.0.3-py3-none-any.whl (20 kB)
Requirement already satisfied: numpy>=1.18.4 in /usr/local/lib/python3.8/dist-packages (from krwordrank) (1.21.6)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.8/dist-packages (from krwordrank) (1.7.3)
Requirement already satisfied: scikit-learn>=0.22.1 in /usr/local/lib/python3.8/dist-packages (from krwordrank) (1.0.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=0.22.1->krwordrank) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=0.22.1->krwordrank) (1.2.0)
Installing collected packages: krwordrank
Successfully installed krwordrank-1.0.3

In [ ]:
import re
from krwordrank.hangle import normalize

In [ ]:
import random

#1168리뷰의 경우 !!가 있다
a = random.randint(0,10000)
df_1.iloc[a,:]

가게                 치킨더홈-서울이대점
맛                           5
양                           5
날짜                 2022-12-19
주문                    후라이드 반＋
사용자id                      11
리뷰       항상 배달도 굿 맛도 양도 굿입니다!
Name: 4194, dtype: object

In [ ]:
 df_temp= df_1.copy()

In [ ]:

df_temp['normalize_doc'] = df_temp['리뷰'].apply(lambda x: ' '.join(re.findall(r'[가-힣]+', str(x))))

# temp_text = df_temp1['normalize_doc'].to_list()
# texts = [normalize(t, english=False, number=False) for t in temp_text]
# df_temp1['normalize_doc2'] = texts

In [ ]:
df_temp[['normalize_doc','normalize_doc2']]

,normalize_doc,normalize_doc2
0,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...
1,맛있어요 너무 맛 어옿,맛있어요 너무 맛 어옿
2,너무 맛있게 잘 먹렀어요 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다,너무 맛있게 잘 먹렀어요 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다
3,굳굳굳 잘 먹었습니당,굳굳굳 잘 먹었습니당
4,시즈닝 팍팍 넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요,시즈닝 팍팍 넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요
...,...,...
12325,잘먹었습니다,잘먹었습니다
12326,맛있어요 튀김도맛있고,맛있어요 튀김도맛있고
12327,바삭바삭한 후라이드 크기부터 남달라요 거기다 맛은 겉바삭 속은 매콤한게 완존 내스타...,바삭바삭한 후라이드 크기부터 남달라요 거기다 맛은 겉바삭 속은 매콤한게 완존 내스타...
12328,맛있게 잘 먹었네요,맛있게 잘 먹었네요
12329,양념 자극적이지 않고 치킨 속살 양념 잘 되어 있어서 간도 잘 맞아요 서비스로 주신...,양념 자극적이지 않고 치킨 속살 양념 잘 되어 있어서 간도 잘 맞아요 서비스로 주신...

In [ ]:
def ddf(df,i) #평점이 높은 i개의 리턴

In [ ]:
df_temp.head()

,가게,맛,양,날짜,주문,사용자id,리뷰,normalize_doc
0,후라이드참잘하는집-서강대점,5,5,2023-02-19,핫간장치킨（무＋소스＋콜라）,st,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...
1,후라이드참잘하는집-서강대점,5,5,2023-02-18,순살 후라이드,yh,맛있어요 너무 맛ㅇㅅ어옿,맛있어요 너무 맛 어옿
2,후라이드참잘하는집-서강대점,5,5,2023-02-17,반마리（순살）,id,너무 맛있게 잘 먹렀어요. 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다.,너무 맛있게 잘 먹렀어요 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다
3,후라이드참잘하는집-서강대점,5,5,2023-02-16,반마리（순살）,rl,굳굳굳 잘 먹었습니당,굳굳굳 잘 먹었습니당
4,후라이드참잘하는집-서강대점,5,5,2023-02-16,핫토스치킨（뼈）（무＋소스＋콜라）,st,시즈닝 팍팍~넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요,시즈닝 팍팍 넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요

In [ ]:
df_temp.shape

(12330, 8)

In [ ]:
#둘다 잘 제거함

df_temp.iloc[4194,:]

가게                         치킨더홈-서울이대점
맛                                   5
양                                   5
날짜                         2022-12-19
주문                            후라이드 반＋
사용자id                              11
리뷰               항상 배달도 굿 맛도 양도 굿입니다!
normalize_doc     항상 배달도 굿 맛도 양도 굿입니다
Name: 4194, dtype: object

In [ ]:
#결측치 없음

df_temp[df_temp['리뷰'].isna()]

Empty DataFrame
Columns: [가게, 맛, 양, 날짜, 주문, 사용자id, 리뷰, normalize_doc]
Index: []

In [ ]:
df_temp.to_csv('df_5_temp.csv',index = False,encoding="utf-8-sig")

# 전처리 부분

1. 치킨 이외의 음식점은 어떻게 처리할지?
ex) 롯데리아등은 치킨이 있어서 이런 데이터도 올라가 있음

2. 리뷰 데이터 전처리
- 이모티콘을 제거할지?? krwordrank등의 라이브러리 활용??
- 리뷰데이터에서 어떻게 하면 키워드만 가져 올 수 있을까??

konlp

krowordrandk

-몇가지를 키워드를 시도해서, 차이를 알아보는
-

# 모델링 

- 신규 사용자에게는 통계적 시스템을 이용한 추천
 - 단순히 평점이 높거나 리뷰수가 많은 치킨집을 추천해줌
 - 이슈) 평점이 대부분 높음 치느님이라서...
  - 그러면 평점이 안좋은 치킨집을 비추천한다면??

- 기존 사용자에게는 협업필터링 방법으로 user_item 행렬을 통한 다른 사용자와의 유사도를 통한 추천 시스템
https://www.youtube.com/watch?v=ZspR5PZemcs&list=LL&index=4


- 자연어 처리 관련해서는 어떤 치킨집을 추천해준다는 결과가 나왔을때 그 치킨집의 리뷰를 분석해서 보여주는 정도??
why) 리뷰 이벤트를 해서 평점만 높을 수도 있어서, 또한 평점이 높아도 리뷰에는 평점으로 표현할 수 없는 단점이나 특성을 추출 할 수 있을 것 같아서


1. 전처리
- ?명이 서로 한번 해보자


2. 통계적 추천시스템 ex) 평균, 최빈값등등
 - 치킨집 10개를 추천
 - 재미삼아) 어떤곳은 걸러라
 - 

3. matrix_factorization
- 단점) 콜드스타


4. 자연어 처리를 통한 인사이트 도출
- 위에서 추천한 치킨집에 리뷰에는 어떤 단어가 많이 쓰일까??


이번주 수요일) 전처리 오후 9시반) 회의

이번주 목요일) 통계적 추천시스템

이번주 금요일) mf

28일오후 10시 or 29일 아침) 완성



발표 ) 안지완 최영우
ppt ) 윤선영, 김주은

## 가설??

1. 그냥 고민하지 말고 프렌차이즈 치킨을 시키는 것이 좋을까??

2. 평점이 좋으면 리뷰도 좋은 리뷰만 있을까??
    - 리뷰이벤트??

3. 양과 맛의 평점의 경우 동일할까? 아니면 양은 많은데 맛은 안좋은 집도 있을까??

4. 치킨을 언제 많이 시켜먹을까?? 불금에 치킨일까??


- 3점이나 2점이나의 리뷰등은 키워드가 다양함
- 치킨집은 치느님이니 보정이 있을까??
   - 낮은 리뷰만 보자

In [ ]:
df_temp.head(10)

,가게,맛,양,날짜,주문,사용자id,리뷰,normalize_doc
0,후라이드참잘하는집-서강대점,5,5,2023-02-19,핫간장치킨（무＋소스＋콜라）,st,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...
1,후라이드참잘하는집-서강대점,5,5,2023-02-18,순살 후라이드,yh,맛있어요 너무 맛ㅇㅅ어옿,맛있어요 너무 맛 어옿
2,후라이드참잘하는집-서강대점,5,5,2023-02-17,반마리（순살）,id,너무 맛있게 잘 먹렀어요. 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다.,너무 맛있게 잘 먹렀어요 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다
3,후라이드참잘하는집-서강대점,5,5,2023-02-16,반마리（순살）,rl,굳굳굳 잘 먹었습니당,굳굳굳 잘 먹었습니당
4,후라이드참잘하는집-서강대점,5,5,2023-02-16,핫토스치킨（뼈）（무＋소스＋콜라）,st,시즈닝 팍팍~넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요,시즈닝 팍팍 넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요
5,후라이드참잘하는집-서강대점,5,5,2023-02-15,반반치킨（후라이드반＋,ye,맛있게 먹었어요!!,맛있게 먹었어요
6,후라이드참잘하는집-서강대점,5,5,2023-02-15,후라이드（무＋소스＋콜라）,23,맛있게 잘 먹었어요,맛있게 잘 먹었어요
7,후라이드참잘하는집-서강대점,5,5,2023-02-14,반반치킨（후라이드반＋,se,11시 넘어서 주문했는데도 15분만에 왔어요 맛있게 잘 먹었습니다,시 넘어서 주문했는데도 분만에 왔어요 맛있게 잘 먹었습니다
8,후라이드참잘하는집-서강대점,5,5,2023-02-14,후라이드（무＋소스＋콜라）,23,맛있게 잘 먹었어요,맛있게 잘 먹었어요
9,후라이드참잘하는집-서강대점,5,5,2023-02-13,순살반반치킨（후라이드반＋,lo,말해 모해요… 후참잘임,말해 모해요 후참잘임

In [ ]:
df_temp.head()

,가게,맛,양,날짜,주문,사용자id,리뷰,normalize_doc
0,후라이드참잘하는집-서강대점,5,5,2023-02-19,핫간장치킨（무＋소스＋콜라）,st,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...
1,후라이드참잘하는집-서강대점,5,5,2023-02-18,순살 후라이드,yh,맛있어요 너무 맛ㅇㅅ어옿,맛있어요 너무 맛 어옿
2,후라이드참잘하는집-서강대점,5,5,2023-02-17,반마리（순살）,id,너무 맛있게 잘 먹렀어요. 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다.,너무 맛있게 잘 먹렀어요 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다
3,후라이드참잘하는집-서강대점,5,5,2023-02-16,반마리（순살）,rl,굳굳굳 잘 먹었습니당,굳굳굳 잘 먹었습니당
4,후라이드참잘하는집-서강대점,5,5,2023-02-16,핫토스치킨（뼈）（무＋소스＋콜라）,st,시즈닝 팍팍~넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요,시즈닝 팍팍 넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요

In [ ]:
df_temp['총점']=df_temp['맛']+df_temp['양']

In [ ]:
df_temp.head()

,가게,맛,양,날짜,주문,사용자id,리뷰,normalize_doc,총점
0,후라이드참잘하는집-서강대점,5,5,2023-02-19,핫간장치킨（무＋소스＋콜라）,st,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...,10
1,후라이드참잘하는집-서강대점,5,5,2023-02-18,순살 후라이드,yh,맛있어요 너무 맛ㅇㅅ어옿,맛있어요 너무 맛 어옿,10
2,후라이드참잘하는집-서강대점,5,5,2023-02-17,반마리（순살）,id,너무 맛있게 잘 먹렀어요. 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다.,너무 맛있게 잘 먹렀어요 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다,10
3,후라이드참잘하는집-서강대점,5,5,2023-02-16,반마리（순살）,rl,굳굳굳 잘 먹었습니당,굳굳굳 잘 먹었습니당,10
4,후라이드참잘하는집-서강대점,5,5,2023-02-16,핫토스치킨（뼈）（무＋소스＋콜라）,st,시즈닝 팍팍~넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요,시즈닝 팍팍 넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요,10

In [ ]:
df_temp['등급']=5
df_temp.loc[(df_temp['맛']==5) & (df_temp['양']==5),'등급']=1
df_temp.loc[(df_temp['맛']==5) & (df_temp['양']==4),'등급']=2
df_temp.loc[(df_temp['맛']==4) & (df_temp['양']==5),'등급']=3
df_temp.loc[(df_temp['맛']==4) & (df_temp['양']==4),'등급']=4

In [ ]:
df_temp.head()

,가게,맛,양,날짜,주문,사용자id,리뷰,normalize_doc,총점,등급
0,후라이드참잘하는집-서강대점,5,5,2023-02-19,핫간장치킨（무＋소스＋콜라）,st,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...,10,1
1,후라이드참잘하는집-서강대점,5,5,2023-02-18,순살 후라이드,yh,맛있어요 너무 맛ㅇㅅ어옿,맛있어요 너무 맛 어옿,10,1
2,후라이드참잘하는집-서강대점,5,5,2023-02-17,반마리（순살）,id,너무 맛있게 잘 먹렀어요. 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다.,너무 맛있게 잘 먹렀어요 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다,10,1
3,후라이드참잘하는집-서강대점,5,5,2023-02-16,반마리（순살）,rl,굳굳굳 잘 먹었습니당,굳굳굳 잘 먹었습니당,10,1
4,후라이드참잘하는집-서강대점,5,5,2023-02-16,핫토스치킨（뼈）（무＋소스＋콜라）,st,시즈닝 팍팍~넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요,시즈닝 팍팍 넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요,10,1

In [ ]:
df_temp['등급'].value_counts()

1    11206
5      390
2      249
4      244
3      241
Name: 등급, dtype: int64

In [ ]:
df_temp.to_csv('df_6_final.csv',index = False,encoding="utf-8-sig")

# 통계적 추천 시스템 구현하기

그리고 통계적 추천을 하기전에 EDA로 그래프를 그려보자



- 평점이 높은 순으로 추천해주기
  - mean으로 높은 것 추천
  - 분명 같은 평균이 있을텐데 다음 기준은 리뷰의 평점의 최솟값이 낮은 치킨집??, 
     분산이 낮은 치킨집??
- 등급이 높은 순으로 추천해주기
- 최근리뷰순이 많은 순으로 추천해주기

## 반대로 평점이 낮은 가게 뽑기
- 평점이 높은 순으로 추천해주기
- 등급이 높은 순으로 추천해주기
- 최근리뷰순이 많은 순으로 추천해주기

In [ ]:
df.head(3)

,가게,맛,양,날짜,주문,사용자id,리뷰,normalize_doc,총점,등급
0,후라이드참잘하는집-서강대점,5,5,2023-02-19,핫간장치킨（무＋소스＋콜라）,st,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...,10,1
1,후라이드참잘하는집-서강대점,5,5,2023-02-18,순살 후라이드,yh,맛있어요 너무 맛ㅇㅅ어옿,맛있어요 너무 맛 어옿,10,1
2,후라이드참잘하는집-서강대점,5,5,2023-02-17,반마리（순살）,id,너무 맛있게 잘 먹렀어요. 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다.,너무 맛있게 잘 먹렀어요 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다,10,1

In [ ]:
#df.groupby(['가게']).mean()

#분석해보니 맛 평점은 컬투치킨이 제일 높음
#근데 컬투치킨이 제일 등급점수가 높은것은 아님 
df_group_shop = df.groupby('가게').mean()
df_group_shop.sort_values(by = '맛',ascending = False)

                          맛         양        총점        등급
가게
컬투치킨-연남사랑점         4.976471  4.980392  9.956863  1.074510
베이직프라이드치킨-신촌직영점    4.975862  4.979310  9.955172  1.068966
치킨더홈-서울이대점         4.969466  4.973282  9.942748  1.072519
굽네치킨&피자-남가좌1호점     4.968641  4.979094  9.947735  1.055749
페리카나-홍익대점          4.967078  4.975309  9.942387  1.074074
굽네치킨&피자-서강점        4.966102  4.955932  9.922034  1.125424
맘스터치피자앤치킨-연대점      4.958333  4.947917  9.906250  1.135417
티바두마리치킨-신수서강대점     4.956349  4.900794  9.857143  1.186508
페리카나-합정동점          4.956044  4.972527  9.928571  1.104396
오늘통닭-신촌점           4.951128  4.921053  9.872180  1.176692
쌀통에퐁닭              4.939394  4.930736  9.870130  1.173160
지코바치킨-신촌점          4.936170  4.904255  9.840426  1.148936
굽네치킨&피자-신촌점        4.936170  4.902128  9.838298  1.208511
굽네치킨&피자-이대역점       4.924138  4.906897  9.831034  1.213793
청년치킨-서교점           4.921348  4.913858  9.835206  1.202247
골라먹는3가지맛디디치킨-아현점   4.920139  4.930556  9.850694  1.222222
지코바치킨-남가좌점         4.919118  4.933824  9.852941  1.187500
호치킨-마포래미안푸르지오점     4.917647  4.905882  9.823529  1.152941
마깐마포깐풍기-신촌본점       4.916981  4.796226  9.713208  1.373585
노랑통닭-아현점           4.915493  4.906103  9.821596  1.253521
맥시칸치킨-연희점          4.912879  4.924242  9.837121  1.185606
치킨시대-명지대점          4.910448  4.940299  9.850746  1.119403
페리카나-이대점           4.907407  4.912037  9.819444  1.162037
양념이맛있는순살킹-아현점      4.907216  4.938144  9.845361  1.226804
자담치킨-신촌점           4.898785  4.914980  9.813765  1.218623
이나닭강정-신촌점          4.896907  4.828179  9.725086  1.302405
골라먹는3가지맛디디치킨-연세대점  4.895753  4.911197  9.806950  1.293436
신미경홍대닭갈비3          4.895397  4.907950  9.803347  1.242678
신미불닭발-서울본점         4.895349  4.864341  9.759690  1.337209
후라이드참잘하는집-서강대점     4.894737  4.919298  9.814035  1.245614
지코바치킨-홍대점          4.894273  4.911894  9.806167  1.202643
치킨플러스-성산점          4.889299  4.929889  9.819188  1.188192
BHC-홍대초교점          4.877622  4.902098  9.779720  1.241259
푸라닭-신수점            4.875862  4.896552  9.772414  1.251724
수준이다른치킨-마포신촌점      4.875486  4.883268  9.758755  1.291829
롯데리아-홍대점           4.872340  4.893617  9.765957  1.276596
네네치킨-서교점           4.869565  4.901186  9.770751  1.252964
BHC-연희점            4.865900  4.881226  9.747126  1.275862
가마로강정-광흥창점         4.860558  4.896414  9.756972  1.334661
푸라닭-합정점            4.860465  4.860465  9.720930  1.255814
BHC-신촌점            4.859589  4.859589  9.719178  1.311644
바른치킨-공덕파크자이점       4.855670  4.865979  9.721649  1.350515
강정이기가막혀-연희점        4.847222  4.944444  9.791667  1.361111
피자와치킨의러브레터-서대문점    4.847107  4.917355  9.764463  1.305785
멕시칸치킨-연남점          4.839506  4.925926  9.765432  1.296296
처갓집양념치킨-독립문점       4.837037  4.885185  9.722222  1.277778
순살만공격-마포신촌점        4.831034  4.841379  9.672414  1.337931
치킨플러스-서교점          4.830882  4.930147  9.761029  1.294118
교촌치킨-신촌점           4.812734  4.891386  9.704120  1.337079
BHC-공덕점            4.807560  4.828179  9.635739  1.415808
전국3대치킨오성통닭-마포신촌점   4.802326  4.856589  9.658915  1.344961
지코바치킨-독립문점         4.795539  4.892193  9.687732  1.330855
BBQ-신촌점            4.783133  4.722892  9.506024  1.481928
호식이두마리치킨-명지대점      4.709898  4.802048  9.511945  1.525597
숯미남숯불치킨에미친남자       4.709302  4.697674  9.406977  1.627907

In [ ]:
df_mean_10_idx=df_group_shop.sort_values('맛',ascending = False).head(10).index
df_mean_10_idx

Index(['컬투치킨-연남사랑점', '베이직프라이드치킨-신촌직영점', '치킨더홈-서울이대점', '굽네치킨&피자-남가좌1호점',
       '페리카나-홍익대점', '굽네치킨&피자-서강점', '맘스터치피자앤치킨-연대점', '티바두마리치킨-신수서강대점',
       '페리카나-합정동점', '오늘통닭-신촌점'],
      dtype='object', name='가게')

In [ ]:
good = []
for i in range(df.shape[0]):
  if df.loc[i]['가게'] in df_mean_10_idx.tolist():
    good.append(i)

#good

In [ ]:
df.loc[good,:].groupby('가게').var().sort_values('맛',ascending = True)

                        맛         양        총점        등급
가게
컬투치킨-연남사랑점       0.023066  0.027173  0.065061  0.195214
베이직프라이드치킨-신촌직영점  0.023637  0.027252  0.084489  0.188999
굽네치킨&피자-서강점      0.032861  0.062677  0.140159  0.361766
맘스터치피자앤치킨-연대점    0.040351  0.070943  0.170066  0.349890
페리카나-합정동점        0.053306  0.037915  0.166140  0.292909
오늘통닭-신촌점         0.061753  0.171102  0.368506  0.568662
티바두마리치킨-신수서강대점   0.065816  0.177370  0.338076  0.566670
치킨더홈-서울이대점       0.075692  0.026103  0.130809  0.205449
페리카나-홍익대점        0.081556  0.024181  0.120634  0.184573
굽네치킨&피자-남가좌1호점   0.093419  0.027533  0.175581  0.150727

In [36]:
#평점이 높은 상위 k개의 치킨집을 불러옴
def mean_rem(df,k):
  df_group_shop = df.groupby('가게').mean()
  df_group_shop.sort_values(by = '맛',ascending = False,inplace = True)
  
  return df_group_shop.head(k)

In [37]:
mean_rem(df,5)

                        맛         양        총점        등급
가게
컬투치킨-연남사랑점       4.976471  4.980392  9.956863  1.074510
베이직프라이드치킨-신촌직영점  4.975862  4.979310  9.955172  1.068966
치킨더홈-서울이대점       4.969466  4.973282  9.942748  1.072519
굽네치킨&피자-남가좌1호점   4.968641  4.979094  9.947735  1.055749
페리카나-홍익대점        4.967078  4.975309  9.942387  1.074074

In [34]:
#상위 k개로 추천을 하고 치킨은 어느정도 평점이 높으니 분산이 다음에는 분산이 낮은걸로 적용하자
def var_rem(df,k):
  df_mean_k = mean_rem(df,k)
  print(pd.DataFrame(df_mean_k))
  print("--------------")
  
  df_mean_k_idx = df_mean_k.index
  

  good = []
  for i in range(df.shape[0]):
    if df.loc[i]['가게'] in df_mean_k_idx.tolist():
      good.append(i)
  result =df.loc[good,:].groupby('가게').var().sort_values('맛',ascending = True)
  print('평점이 높은 상위 k개중에 평점의 분산이 낮은 k개의 가게')
  return result

In [38]:
var_rem(df,5)

                        맛         양        총점        등급
가게
컬투치킨-연남사랑점       4.976471  4.980392  9.956863  1.074510
베이직프라이드치킨-신촌직영점  4.975862  4.979310  9.955172  1.068966
치킨더홈-서울이대점       4.969466  4.973282  9.942748  1.072519
굽네치킨&피자-남가좌1호점   4.968641  4.979094  9.947735  1.055749
페리카나-홍익대점        4.967078  4.975309  9.942387  1.074074
--------------
평점이 높은 상위 k개중에 평점의 분산이 낮은 k개의 가게

                        맛         양        총점        등급
가게
컬투치킨-연남사랑점       0.023066  0.027173  0.065061  0.195214
베이직프라이드치킨-신촌직영점  0.023637  0.027252  0.084489  0.188999
치킨더홈-서울이대점       0.075692  0.026103  0.130809  0.205449
페리카나-홍익대점        0.081556  0.024181  0.120634  0.184573
굽네치킨&피자-남가좌1호점   0.093419  0.027533  0.175581  0.150727

최근리뷰에 따라서 추천하기
- 최근의 정의를 뭘로할까? 한달??
- 최근리뷰만 놓고 분석하기(한달내에 평점을 이용하기)
- 최근 리뷰가 많은 순으로 추천하기

In [ ]:
import datetime

In [ ]:
#2023년의 리뷰만 가져오기

year_list = []

for i in range(df.shape[0]):
  if df.loc[i]['날짜'][:4] == '2023':
    year_list.append(i)

In [ ]:
#가져와서 df_2023에 저장
df_2023 = df.loc[year_list,:]

In [ ]:
#최근에 좋다는 것을 알 수 있음. but 전부 5점이고 전부 1등급은 약간 이상함
#원인1) 2023에 리뷰가 1개밖에 없는데도 있음
#따라서 이것만 하면 애매하니 최근리뷰가 많은순으로 추천한다음 거기서 다시 평균과 분산을 쓰는게 맞다.



#리뷰 분석을 통해서 전부 다 좋은지 파악 필요
#분산도 알아보자
#2023에 평점이 낮은데는 뭐지?


df_2023.groupby('가게').mean().sort_values('맛',ascending = False)

                          맛         양         총점        등급
가게
BBQ-신촌점            5.000000  5.000000  10.000000  1.000000
마깐마포깐풍기-신촌본점       5.000000  4.750000   9.750000  1.500000
푸라닭-합정점            5.000000  5.000000  10.000000  1.000000
페리카나-홍익대점          5.000000  5.000000  10.000000  1.000000
페리카나-이대점           5.000000  5.000000  10.000000  1.000000
컬투치킨-연남사랑점         5.000000  5.000000  10.000000  1.000000
치킨더홈-서울이대점         5.000000  5.000000  10.000000  1.000000
전국3대치킨오성통닭-마포신촌점   5.000000  5.000000  10.000000  1.000000
자담치킨-신촌점           5.000000  4.857143   9.857143  1.142857
쌀통에퐁닭              5.000000  5.000000  10.000000  1.000000
멕시칸치킨-연남점          5.000000  5.000000  10.000000  1.000000
맥시칸치킨-연희점          5.000000  5.000000  10.000000  1.000000
신미불닭발-서울본점         5.000000  5.000000  10.000000  1.000000
굽네치킨&피자-신촌점        5.000000  5.000000  10.000000  1.000000
가마로강정-광흥창점         5.000000  5.000000  10.000000  1.000000
강정이기가막혀-연희점        5.000000  5.000000  10.000000  1.000000
베이직프라이드치킨-신촌직영점    4.990476  5.000000   9.990476  1.019048
청년치킨-서교점           4.967742  4.967742   9.935484  1.096774
굽네치킨&피자-서강점        4.964912  4.938596   9.903509  1.149123
오늘통닭-신촌점           4.961538  4.884615   9.846154  1.243590
굽네치킨&피자-남가좌1호점     4.954545  4.954545   9.909091  1.068182
맘스터치피자앤치킨-연대점      4.945946  4.932432   9.878378  1.175676
푸라닭-신수점            4.938776  4.959184   9.897959  1.163265
지코바치킨-남가좌점         4.936170  4.978723   9.914894  1.148936
지코바치킨-신촌점          4.936170  4.904255   9.840426  1.148936
골라먹는3가지맛디디치킨-연세대점  4.933333  4.933333   9.866667  1.200000
이나닭강정-신촌점          4.930556  4.805556   9.736111  1.291667
BHC-연희점            4.923077  4.923077   9.846154  1.230769
굽네치킨&피자-이대역점       4.918819  4.900369   9.819188  1.228782
숯미남숯불치킨에미친남자       4.916667  4.833333   9.750000  1.333333
노랑통닭-아현점           4.903226  4.919355   9.822581  1.241935
후라이드참잘하는집-서강대점     4.902439  4.926829   9.829268  1.207317
티바두마리치킨-신수서강대점     4.900000  4.700000   9.600000  1.500000
지코바치킨-홍대점          4.900000  4.933333   9.833333  1.200000
양념이맛있는순살킹-아현점      4.900000  5.000000   9.900000  1.200000
롯데리아-홍대점           4.896552  4.896552   9.793103  1.137931
페리카나-합정동점          4.894737  4.947368   9.842105  1.263158
호치킨-마포래미안푸르지오점     4.888889  4.833333   9.722222  1.222222
수준이다른치킨-마포신촌점      4.882353  4.941176   9.823529  1.235294
교촌치킨-신촌점           4.882353  4.911765   9.794118  1.147059
바른치킨-공덕파크자이점       4.878049  4.878049   9.756098  1.341463
BHC-홍대초교점          4.872247  4.907489   9.779736  1.237885
신미경홍대닭갈비3          4.869565  4.913043   9.782609  1.260870
순살만공격-마포신촌점        4.866667  4.866667   9.733333  1.133333
골라먹는3가지맛디디치킨-아현점   4.861111  4.875000   9.736111  1.402778
네네치킨-서교점           4.850000  4.900000   9.750000  1.250000
BHC-신촌점            4.848485  4.863636   9.712121  1.333333
치킨플러스-성산점          4.842466  4.910959   9.753425  1.226027
피자와치킨의러브레터-서대문점    4.833333  5.000000   9.833333  1.333333
BHC-공덕점            4.831776  4.831776   9.663551  1.364486
지코바치킨-독립문점         4.763889  4.847222   9.611111  1.388889
호식이두마리치킨-명지대점      4.714286  4.732143   9.446429  1.553571
치킨플러스-서교점          4.701299  4.909091   9.610390  1.480519
치킨시대-명지대점          4.692308  4.692308   9.384615  1.307692
처갓집양념치킨-독립문점       4.671429  4.814286   9.485714  1.414286

In [ ]:
df_2023.groupby('가게').var().sort_values('맛',ascending = False)

                          맛         양        총점        등급
가게
치킨시대-명지대점          1.230769  1.230769  4.923077  1.230769
처갓집양념치킨-독립문점       1.035404  0.530228  2.862112  1.405590
치킨플러스-서교점          0.685919  0.267943  1.530417  1.358168
호식이두마리치킨-명지대점      0.644156  0.599675  2.360714  1.778896
지코바치킨-독립문점         0.549100  0.553795  2.015649  1.086072
순살만공격-마포신촌점        0.533333  0.533333  2.133333  0.533333
교촌치킨-신촌점           0.470588  0.143494  1.077540  0.492870
치킨플러스-성산점          0.437081  0.233396  1.221540  0.672697
BHC-공덕점            0.405396  0.386528  1.414036  0.988538
네네치킨-서교점           0.382278  0.268354  1.177215  0.822785
BHC-신촌점            0.345921  0.150350  0.885082  0.964103
BHC-홍대초교점          0.324315  0.181669  0.836225  0.766169
롯데리아-홍대점           0.310345  0.310345  1.241379  0.551724
신미경홍대닭갈비3          0.274833  0.225960  0.711520  0.821961
후라이드참잘하는집-서강대점     0.261969  0.118037  0.563083  0.758958
수준이다른치킨-마포신촌점      0.235294  0.058824  0.529412  0.941176
호치킨-마포래미안푸르지오점     0.222222  0.500000  1.388889  0.888889
지코바치킨-신촌점          0.210936  0.238046  0.823725  0.515214
골라먹는3가지맛디디치킨-아현점   0.205790  0.167254  0.535016  1.201682
노랑통닭-아현점           0.187203  0.075357  0.312269  0.612639
굽네치킨&피자-남가좌1호점     0.181818  0.066876  0.428422  0.202194
굽네치킨&피자-이대역점       0.171163  0.149296  0.467186  0.651169
지코바치킨-홍대점          0.162069  0.133333  0.557471  0.648276
바른치킨-공덕파크자이점       0.159756  0.259756  0.589024  1.030488
피자와치킨의러브레터-서대문점    0.151515  0.000000  0.151515  0.606061
이나닭강정-신촌점          0.150039  0.440532  0.901213  0.913732
지코바치킨-남가좌점         0.104533  0.021277  0.166512  0.520814
티바두마리치킨-신수서강대점     0.100000  0.233333  0.488889  0.944444
페리카나-합정동점          0.099415  0.052632  0.251462  0.649123
양념이맛있는순살킹-아현점      0.094737  0.000000  0.094737  0.378947
숯미남숯불치킨에미친남자       0.083333  0.151515  0.386364  0.787879
BHC-연희점            0.076923  0.076923  0.307692  0.692308
골라먹는3가지맛디디치킨-연세대점  0.066667  0.066667  0.266667  0.600000
푸라닭-신수점            0.058673  0.039966  0.135204  0.347789
청년치킨-서교점           0.053296  0.031557  0.082749  0.240533
맘스터치피자앤치킨-연대점      0.051833  0.091262  0.217882  0.448167
오늘통닭-신촌점           0.037463  0.207293  0.339660  0.835997
굽네치킨&피자-서강점        0.034156  0.093541  0.176448  0.428893
베이직프라이드치킨-신촌직영점    0.009524  0.000000  0.009524  0.038095
페리카나-홍익대점          0.000000  0.000000  0.000000  0.000000
푸라닭-합정점            0.000000  0.000000  0.000000  0.000000
페리카나-이대점           0.000000  0.000000  0.000000  0.000000
마깐마포깐풍기-신촌본점       0.000000  0.500000  0.500000  2.000000
컬투치킨-연남사랑점         0.000000  0.000000  0.000000  0.000000
강정이기가막혀-연희점        0.000000  0.000000  0.000000  0.000000
치킨더홈-서울이대점         0.000000  0.000000  0.000000  0.000000
전국3대치킨오성통닭-마포신촌점   0.000000  0.000000  0.000000  0.000000
자담치킨-신촌점           0.000000  0.142857  0.142857  0.142857
굽네치킨&피자-신촌점        0.000000  0.000000  0.000000  0.000000
신미불닭발-서울본점         0.000000  0.000000  0.000000  0.000000
멕시칸치킨-연남점          0.000000  0.000000  0.000000  0.000000
맥시칸치킨-연희점          0.000000  0.000000  0.000000  0.000000
쌀통에퐁닭              0.000000  0.000000  0.000000  0.000000
BBQ-신촌점                 NaN       NaN       NaN       NaN
가마로강정-광흥창점              NaN       NaN       NaN       NaN

In [ ]:
#평점이 너무 높고 분산이 0이길레 보니 이런문제 발생


df_2023[df_2023['가게'] == '자담치킨-신촌점']['맛'].value_counts()

5    7
Name: 맛, dtype: int64

In [ ]:
df_2023.groupby('가게').count().sort_values('리뷰',ascending = False)

                     맛    양   날짜   주문  사용자id   리뷰  normalize_doc   총점   등급
가게
굽네치킨&피자-이대역점       271  271  271  271    271  271            271  271  271
BHC-홍대초교점          227  227  227  227    227  227            226  227  227
치킨플러스-성산점          146  146  146  146    146  146            145  146  146
신미경홍대닭갈비3          138  138  138  138    138  138            137  138  138
굽네치킨&피자-서강점        114  114  114  114    114  114            114  114  114
BHC-공덕점            107  107  107  107    107  107            106  107  107
베이직프라이드치킨-신촌직영점    105  105  105  105    105  105            104  105  105
컬투치킨-연남사랑점          97   97   97   97     97   97             96   97   97
지코바치킨-신촌점           94   94   94   94     94   94             93   94   94
청년치킨-서교점            93   93   93   93     93   93             92   93   93
굽네치킨&피자-남가좌1호점      88   88   88   88     88   88             88   88   88
후라이드참잘하는집-서강대점      82   82   82   82     82   82             82   82   82
네네치킨-서교점            80   80   80   80     80   80             79   80   80
오늘통닭-신촌점            78   78   78   78     78   78             77   78   78
치킨플러스-서교점           77   77   77   77     77   77             76   77   77
맘스터치피자앤치킨-연대점       74   74   74   74     74   74             74   74   74
지코바치킨-독립문점          72   72   72   72     72   72             72   72   72
이나닭강정-신촌점           72   72   72   72     72   72             71   72   72
골라먹는3가지맛디디치킨-아현점    72   72   72   72     72   72             71   72   72
처갓집양념치킨-독립문점        70   70   70   70     70   70             68   70   70
치킨더홈-서울이대점          68   68   68   68     68   68             66   68   68
BHC-신촌점             66   66   66   66     66   66             65   66   66
노랑통닭-아현점            62   62   62   62     62   62             62   62   62
호식이두마리치킨-명지대점       56   56   56   56     56   56             55   56   56
푸라닭-신수점             49   49   49   49     49   49             49   49   49
지코바치킨-남가좌점          47   47   47   47     47   47             47   47   47
바른치킨-공덕파크자이점        41   41   41   41     41   41             41   41   41
교촌치킨-신촌점            34   34   34   34     34   34             34   34   34
지코바치킨-홍대점           30   30   30   30     30   30             30   30   30
순살만공격-마포신촌점         30   30   30   30     30   30             29   30   30
롯데리아-홍대점            29   29   29   29     29   29             28   29   29
신미불닭발-서울본점          28   28   28   28     28   28             28   28   28
양념이맛있는순살킹-아현점       20   20   20   20     20   20             20   20   20
페리카나-합정동점           19   19   19   19     19   19             19   19   19
호치킨-마포래미안푸르지오점      18   18   18   18     18   18             17   18   18
수준이다른치킨-마포신촌점       17   17   17   17     17   17             17   17   17
굽네치킨&피자-신촌점         17   17   17   17     17   17             17   17   17
쌀통에퐁닭               16   16   16   16     16   16             16   16   16
골라먹는3가지맛디디치킨-연세대점   15   15   15   15     15   15             15   15   15
페리카나-홍익대점           13   13   13   13     13   13             13   13   13
치킨시대-명지대점           13   13   13   13     13   13             13   13   13
BHC-연희점             13   13   13   13     13   13             13   13   13
숯미남숯불치킨에미친남자        12   12   12   12     12   12             12   12   12
맥시칸치킨-연희점           12   12   12   12     12   12             11   12   12
피자와치킨의러브레터-서대문점     12   12   12   12     12   12             12   12   12
티바두마리치킨-신수서강대점      10   10   10   10     10   10             10   10   10
마깐마포깐풍기-신촌본점         8    8    8    8      8    8              7    8    8
전국3대치킨오성통닭-마포신촌점     8    8    8    8      8    8              8    8    8
자담치킨-신촌점             7    7    7    7      7    7              7    7    7
페리카나-이대점             6    6    6    6      6    6              6    6    6
강정이기가막혀-연희점          4    4    4    4      4    4              4    4    4
멕시칸치킨-연남점            3    3    3    3      3    3              3    3    3
푸라닭-합정점              2    2    2    2      2    2              2    2    2
가마로강정-광흥창점           1    1    1    1      1    1              1    1    1
BBQ-신촌점              1    1    1    1      1    1              1    1    1

In [ ]:
year_idx = df_2023.groupby('가게').count().sort_values('리뷰',ascending = False).head(10).index

In [ ]:
df_res_year=[]
for i in range(df.shape[0]):
  if df.loc[i]['가게'] in year_idx.tolist():
    df_res_year.append(i)

df_year_final = df.loc[df_res_year,:]

In [ ]:
df_year_final.groupby('가게').var().sort_values('맛',ascending= True)

                        맛         양        총점        등급
가게
컬투치킨-연남사랑점       0.023066  0.027173  0.065061  0.195214
베이직프라이드치킨-신촌직영점  0.023637  0.027252  0.084489  0.188999
굽네치킨&피자-서강점      0.032861  0.062677  0.140159  0.361766
청년치킨-서교점         0.155445  0.191800  0.529132  0.583002
굽네치킨&피자-이대역점     0.160315  0.140091  0.438480  0.611574
지코바치킨-신촌점        0.210936  0.238046  0.823725  0.515214
신미경홍대닭갈비3        0.211701  0.193172  0.562006  0.713969
치킨플러스-성산점        0.283996  0.146918  0.741260  0.523712
BHC-홍대초교점        0.318305  0.179855  0.824991  0.773169
BHC-공덕점          0.418012  0.322100  1.239270  1.133404

In [32]:
def review_rem(df,k):
  year_idx = df.groupby('가게').count().sort_values('리뷰',ascending = False).head(k).index
  df_res_year=[]
  for i in range(df.shape[0]):
    if df.loc[i]['가게'] in year_idx.tolist():
      df_res_year.append(i)

  df_year_final = df.loc[df_res_year,:]
  res =df_year_final.groupby('가게').var().sort_values('맛',ascending= True)

  return res

In [33]:
review_rem(df,10)

                         맛         양        총점        등급
가게
베이직프라이드치킨-신촌직영점   0.023637  0.027252  0.084489  0.188999
굽네치킨&피자-서강점       0.032861  0.062677  0.140159  0.361766
골라먹는3가지맛디디치킨-아현점  0.101614  0.085753  0.294703  0.612466
굽네치킨&피자-이대역점      0.160315  0.140091  0.438480  0.611574
이나닭강정-신촌점         0.251404  0.301410  0.903472  0.846167
BHC-신촌점           0.292932  0.279186  1.068634  0.936909
푸라닭-신수점           0.323637  0.183033  0.819998  0.756485
순살만공격-마포신촌점       0.417719  0.396898  1.480551  0.978833
BHC-공덕점           0.418012  0.322100  1.239270  1.133404
호식이두마리치킨-명지대점     0.631306  0.460681  1.880850  1.510473

# mf를 이용한 협업필터링으로 추천하기
- pivot-table를 만들기 
- rmse를 구하고 추천해보기
- surprise를 이용해서 추천하기

In [39]:
df.head()

,가게,맛,양,날짜,주문,사용자id,리뷰,normalize_doc,총점,등급
0,후라이드참잘하는집-서강대점,5,5,2023-02-19,핫간장치킨（무＋소스＋콜라）,st,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...,주문해놓고 샤워하고 나왔는데 바로 왔음 배달은 항상 빨라서 좋고 맛은 말할거 없이 ...,10,1
1,후라이드참잘하는집-서강대점,5,5,2023-02-18,순살 후라이드,yh,맛있어요 너무 맛ㅇㅅ어옿,맛있어요 너무 맛 어옿,10,1
2,후라이드참잘하는집-서강대점,5,5,2023-02-17,반마리（순살）,id,너무 맛있게 잘 먹렀어요. 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다.,너무 맛있게 잘 먹렀어요 머스터드 소스 넉넉히 주셔수 모자라지 않게 잘 먹었습니다,10,1
3,후라이드참잘하는집-서강대점,5,5,2023-02-16,반마리（순살）,rl,굳굳굳 잘 먹었습니당,굳굳굳 잘 먹었습니당,10,1
4,후라이드참잘하는집-서강대점,5,5,2023-02-16,핫토스치킨（뼈）（무＋소스＋콜라）,st,시즈닝 팍팍~넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요,시즈닝 팍팍 넘 맛있었요 간만에 치킨 먹은건데 기분좋게 먹었어요,10,1

In [4]:
import numpy as np
from sklearn.metrics import mean_squared_error

def get_rmse(R, P, Q, non_zeros):
    error = 0
    # 두개의 분해된 행렬 P와 Q.T의 내적 곱으로 예측 R 행렬 생성
    full_pred_matrix = np.dot(P, Q.T)
    
    # 실제 R 행렬에서 널이 아닌 값의 위치 인덱스 추출하여 실제 R 행렬과 예측 행렬의 RMSE 추출
    x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
    R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]
    
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]
      
    mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
    rmse = np.sqrt(mse)
    
    return rmse

In [5]:
#R은 기존 평점 행렬
#K는 P,Q를 초기화하기 위한 상수


def matrix_factorization(R, K, steps=200, learning_rate=0.01, r_lambda = 0.01):
    num_users, num_items = R.shape
    # P와 Q 매트릭스의 크기를 지정하고 정규분포를 가진 랜덤한 값으로 입력합니다. 
    np.random.seed(1)
    P = np.random.normal(scale=1./K, size=(num_users, K))
    Q = np.random.normal(scale=1./K, size=(num_items, K))

    break_count = 0
       
    # R > 0 인 행 위치, 열 위치, 값을 non_zeros 리스트 객체에 저장. 
    # NON-ZERO: 사용자가 먹은 치킨들만 따로 행렬을 만들음
    non_zeros = [ (i, j, R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j] > 0 ]
   
    # SGD기법으로 P와 Q 매트릭스를 계속 업데이트. 
    for step in range(steps):
        for i, j, r in non_zeros:
            # 실제 값과 예측 값의 차이인 오류 값 구함
            eij = r - np.dot(P[i, :], Q[j, :].T)
            # Regularization을 반영한 SGD 업데이트 공식 적용
            P[i,:] = P[i,:] + learning_rate*(eij * Q[j, :] - r_lambda*P[i,:])
            Q[j,:] = Q[j,:] + learning_rate*(eij * P[i, :] - r_lambda*Q[j,:])
       
        rmse = get_rmse(R, P, Q, non_zeros)
        if (step % 10) == 0 :
            print("### iteration step : ", step," rmse : ", rmse)
            
    return P, Q

user_item 행렬을 위해서 pivot_table로 데이터 변형하기

In [6]:
ratings_matrix = df.pivot_table('맛', index='사용자id', columns='주문')

In [7]:
ratings_matrix

주문,1.순살후라이드＋순살후라이드＋콜라1.25L,100% 가평잣으로 만든 고소치킨,100%청,1마리 3가지맛세트 오리지널,1마리 3가지맛세트 오리지널（순살）,1마리 3가지맛세트 오리지널＋리틀꿔바로우,1마리 3가지맛세트 오리지널＋포테이토치즈볼（5개）,1마리 3가지맛세트 오리지널＋한입붕어빵（6개）,1마리 3가지맛세트 오리지널＋후루룩떡볶이,1마리 골라먹는 3가지맛세트,...,（후라이드 순살）빠삭킹 마늘 간장 반마리,（후라이드 순살）빠삭킹 반마리,（후라이드 순살）빠삭킹 화이트 크림 반마리,（후라이드치킨）,（후라이드치킨）（중）,（후라이드）빠삭킹 눈꽃치즈 반 반 （추천메뉴）,（후라이드）빠삭킹 마늘간장 반 반 （추천메뉴）,（후라이드）빠삭킹 볼케이노 반 반 （매운맛마니아）,（후라이드）빠삭킹 오리지널,（후라이드）빠삭킹（판매1위）
사용자id,,,,,,,,,,,,,,,,,,,,,
-_,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-e,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
-s,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zv,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#best rmse :  0.04969558738935449
#P,Q를 만들고 SGD방법으로 에러 갱신하기 (평가지표 RMSE)
#만들어진 PQ를 가지고 곱해서 예측 행렬 만들기

P, Q = matrix_factorization(ratings_matrix.values, K=50, steps=200, learning_rate=0.01, r_lambda = 0.01)
pred_matrix = np.dot(P, Q.T)

### iteration step :  0  rmse :  4.8951221380869105
### iteration step :  10  rmse :  1.2430796012716565
### iteration step :  20  rmse :  0.690406339269562
### iteration step :  30  rmse :  0.4650977916214984
### iteration step :  40  rmse :  0.3418230823095762
### iteration step :  50  rmse :  0.2620866359238788
### iteration step :  60  rmse :  0.19978957187206126
### iteration step :  70  rmse :  0.1525514729247504
### iteration step :  80  rmse :  0.12266125979746145
### iteration step :  90  rmse :  0.10412970851938211
### iteration step :  100  rmse :  0.09133001269191322
### iteration step :  110  rmse :  0.08173631565860187
### iteration step :  120  rmse :  0.07423183450591636
### iteration step :  130  rmse :  0.06823198790212999
### iteration step :  140  rmse :  0.063386634942216
### iteration step :  150  rmse :  0.05945658868810413
### iteration step :  160  rmse :  0.056257874551176285
### iteration step :  170  rmse :  0.05364106082678603
### iteration step :  180  rmse :  0.051485376146271945
### iteration step :  190  rmse :  0.04969558738935449

In [9]:
#예측된 행렬을 데이터 프레임화하기

ratings_pred_matrix = pd.DataFrame(data=pred_matrix, index= ratings_matrix.index,
                                   columns = ratings_matrix.columns)

ratings_pred_matrix.head(3)

주문,1.순살후라이드＋순살후라이드＋콜라1.25L,100% 가평잣으로 만든 고소치킨,100%청,1마리 3가지맛세트 오리지널,1마리 3가지맛세트 오리지널（순살）,1마리 3가지맛세트 오리지널＋리틀꿔바로우,1마리 3가지맛세트 오리지널＋포테이토치즈볼（5개）,1마리 3가지맛세트 오리지널＋한입붕어빵（6개）,1마리 3가지맛세트 오리지널＋후루룩떡볶이,1마리 골라먹는 3가지맛세트,...,（후라이드 순살）빠삭킹 마늘 간장 반마리,（후라이드 순살）빠삭킹 반마리,（후라이드 순살）빠삭킹 화이트 크림 반마리,（후라이드치킨）,（후라이드치킨）（중）,（후라이드）빠삭킹 눈꽃치즈 반 반 （추천메뉴）,（후라이드）빠삭킹 마늘간장 반 반 （추천메뉴）,（후라이드）빠삭킹 볼케이노 반 반 （매운맛마니아）,（후라이드）빠삭킹 오리지널,（후라이드）빠삭킹（판매1위）
사용자id,,,,,,,,,,,,,,,,,,,,,
-_,-0.788467,-0.806807,-0.658785,-0.703460,-1.052506,-0.925340,-0.762857,-0.717976,-1.050631,-0.989366,...,-0.860107,-0.899358,-0.691309,-0.721431,-1.015710,-0.766502,-0.937184,-0.798003,-0.811729,-1.085890
-e,4.395710,4.690197,4.754406,4.473397,4.326188,4.623029,4.477617,4.724177,4.638267,4.666176,...,4.783581,4.809980,4.456288,4.281546,4.335644,4.536896,4.665877,4.763913,4.754344,4.722803
-s,2.496350,2.676966,2.769166,2.552517,2.441162,2.640338,2.609603,2.749857,2.748706,2.663645,...,2.691454,2.733935,2.473551,2.340797,2.258727,2.584742,2.653170,2.715398,2.725743,2.748924

In [10]:
df['사용자id'].unique

<bound method Series.unique of 0        st
1        yh
2        id
3        rl
4        st
         ..
12325    ju
12326    sn
12327    ny
12328    im
12329    wk
Name: 사용자id, Length: 12330, dtype: object>

In [11]:

def get_unate_food(ratings_matrix, userId):
    # userId로 입력받은 사용자의 모든 치킨을 주문한 정보를 추출하여 Series로 반환함. 
    # 반환된 user_rating 은 메뉴이름(주문)을 index로 가지는 Series 객체임. 
    user_rating = ratings_matrix.loc[userId,:]
    
    # user_rating이 0보다 크면 주문한 치킨임. 대상 index를 추출하여 list 객체로 만듬
    already_ate = user_rating[ user_rating > 0].index.tolist()
    
    # 모든 영화명을 list 객체로 만듬. 
    order_list = ratings_matrix.columns.tolist()
    

    unate_list = [ food for food in order_list if food not in already_ate]
    
    return unate_list

In [12]:

def recomm_movie_by_userid(pred_df, userId, unseen_list, top_n=10):
    # 예측 평점 DataFrame에서 사용자id index와 unseen_list로 들어온 치킨 이름을 추출하여
    # 가장 예측 평점이 높은 순으로 정렬함. 
    recomm_chicken = pred_df.loc[userId, unseen_list].sort_values(ascending=False)[:top_n]
    return recomm_chicken

In [13]:
# 'yh'라는 사용자가 먹어보지 않은 치킨리스트 만들기 
unseen_list = get_unate_food(ratings_matrix, 'yh')

# 아이템 기반의 인접 이웃 협업 필터링으로 영화 추천 
recomm_chicken = recomm_movie_by_userid(ratings_pred_matrix, 'yh', unseen_list, top_n=10)

# 평점 데이타를 DataFrame으로 생성. 
recomm_chickens = pd.DataFrame(data=recomm_chicken.values,index=recomm_chicken.index,columns=['pred_score'])
recomm_chickens

                       pred_score
주문
고추마요 치킨                  5.291954
순살 핫슈프림                  5.222842
크리스피치킨                   5.148188
반반순살（매운맛）                5.094134
반반（매콤강정＋달콤강정）            5.031079
순살 블랙마요                  4.988696
이나닭강정（중）＋이나사이드메뉴 （선택）    4.983678
후라이드 콤보                  4.962895
슈프림                      4.958212
（후라이드）빠삭킹（판매1위）          4.937465

In [14]:
pip install surprise

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting surprise
  Downloading surprise-0.1-py2.py3-none-any.whl (1.8 kB)
Collecting scikit-surprise
  Downloading scikit-surprise-1.1.3.tar.gz (771 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 772.0/772.0 KB 14.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: joblib>=1.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-surprise->surprise) (1.2.0)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from scikit-surprise->surprise) (1.22.4)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.8/dist-packages (from scikit-surprise->surprise) (1.7.3)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (setup.py) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.3-cp38-cp38-linux_x86_64.whl size=3366548 sha256=0229df5ecbfe2ae7dd7708af6bdca83fa03727480cecd6e3857879bcae6f9eb2
  Stored in directory: /root/.cache/pip/wheels/af/db/86/2c18183a80ba05da35bf0fb7417aac5cddbd93bcb1b92fd3ea
Successfully built scikit-surprise
Installing collected packages: scikit-surprise, surprise
Successfully installed scikit-surprise-1.1.3 surprise-0.1

In [15]:
import surprise

In [16]:
from surprise import SVD
from surprise import Dataset 
from surprise import accuracy 
from surprise.model_selection import train_test_split

In [17]:
df_sus = df[['사용자id','주문','맛']]
df_sus.head()

  사용자id                 주문  맛
0    st     핫간장치킨（무＋소스＋콜라）  5
1    yh            순살 후라이드  5
2    id            반마리（순살）  5
3    rl            반마리（순살）  5
4    st  핫토스치킨（뼈）（무＋소스＋콜라）  5

일반데이터는 안되니 해당 주소를 참조해서 새롭게 데이터를 가공해서 사용하기
- surprise라이브러리를 사용하려면 칼럼은 userid,itemid,ratings의 순으로 있어야 하고 기존의 판다스 데이터 프레임은 사용못함
- https://github.com/NicolasHug/Surprise/issues/20

In [18]:
df_sus.columns = ['userID','itemID','rating']

In [19]:
from surprise import Reader
reader = Reader(line_format='user item rating', rating_scale=(1, 5))

In [20]:
from surprise import dataset


class MyDataset(dataset.DatasetAutoFolds):

    def __init__(self, df, reader):

        self.raw_ratings = [(uid, iid, r, None) for (uid, iid, r) in
                            zip(df['userID'], df['itemID'], df['rating'])]
        self.reader=reader

In [21]:
data = MyDataset(df_sus, reader)

In [22]:
trainset, testset = train_test_split(data, test_size=.25, random_state=0)

In [23]:
trainset

svd() 객체 선언하고 해당 데이터를 학습시키기

In [24]:
algo = SVD()
algo.fit(trainset)

In [25]:
predictions = algo.test( testset )
print('prediction type :',type(predictions), ' size:',len(predictions))
print('prediction 결과의 최초 5개 추출')
predictions[:5]

prediction type : <class 'list'>  size: 3083
prediction 결과의 최초 5개 추출

[Prediction(uid='sh', iid='무뼈닭발Set', r_ui=5, est=4.888928987127884, details={'was_impossible': False}),
 Prediction(uid='qk', iid='순살', r_ui=5, est=4.907300569889438, details={'was_impossible': False}),
 Prediction(uid='pd', iid='순살', r_ui=5, est=4.8651341714687035, details={'was_impossible': False}),
 Prediction(uid='jo', iid='핫후라이드', r_ui=5, est=4.82537272000146, details={'was_impossible': False}),
 Prediction(uid='pj', iid='내맘대로 순살 세가지맛', r_ui=5, est=4.872896856552449, details={'was_impossible': False})]

교차검증과 하이퍼파라미터 튜닝

In [26]:
from surprise.model_selection import cross_validate 


algo = SVD(random_state=0) 
cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std
RMSE (testset)    0.5100  0.4756  0.5185  0.4793  0.4938  0.4954  0.0168
MAE (testset)     0.2146  0.2011  0.2120  0.1987  0.2062  0.2065  0.0061
Fit time          0.11    0.11    0.11    0.11    0.11    0.11    0.00
Test time         0.01    0.02    0.01    0.01    0.01    0.02    0.00

{'test_rmse': array([0.51000291, 0.4755906 , 0.51852807, 0.47927551, 0.49381927]),
 'test_mae': array([0.21459068, 0.20107836, 0.21195065, 0.19873573, 0.20623247]),
 'fit_time': (0.10604453086853027,
  0.10762643814086914,
  0.10975813865661621,
  0.10851478576660156,
  0.10740971565246582),
 'test_time': (0.014735698699951172,
  0.01955866813659668,
  0.01412820816040039,
  0.014069557189941406,
  0.01291036605834961)}

In [27]:
from surprise.model_selection import GridSearchCV

# 최적화할 파라미터들을 딕셔너리 형태로 지정. 
param_grid = {'n_epochs': [10,20, 40, 60], 'n_factors': [10,30,50, 100, 200] }
#param_grid = {'n_epochs': [3,5,7,10], 'n_factors': [3,5,7,10] }



# CV를 3개 폴드 세트로 지정, 성능 평가는 rmse, mse 로 수행 하도록 GridSearchCV 구성
gs = GridSearchCV(SVD, param_grid, measures=['rmse', 'mae'], cv=3)
gs.fit(data)

# 최고 RMSE Evaluation 점수와 그때의 하이퍼 파라미터
print(gs.best_score['rmse'])
print(gs.best_params['rmse'])

0.49089338304993246
{'n_epochs': 10, 'n_factors': 10}

0.48739666970845946
{'n_epochs': 3, 'n_factors': 3}

In [28]:
df_sus.head()

  userID             itemID  rating
0     st     핫간장치킨（무＋소스＋콜라）       5
1     yh            순살 후라이드       5
2     id            반마리（순살）       5
3     rl            반마리（순살）       5
4     st  핫토스치킨（뼈）（무＋소스＋콜라）       5

In [29]:
def get_unate_surprise(ratings, userId):
    #입력값으로 들어온 userId에 해당하는 사용자가 평점을 매긴 모든 치킨을 리스트로 생성
    # seen_movies = ratings[ratings['userId']== userId]['movieId'].tolist()
    ate_chickens = ratings[ratings['userID']== userId]['itemID'].tolist()
    
    # 모든 영화들의 movieId를 리스트로 생성. 
    #total_movies = movies['movieId'].tolist()
    total_food = ratings['itemID'].unique().tolist()

    # 모든 치킨들중 이미 평점을 매긴 치킨을 제외하여 리스트로 생성
    #unseen_movies= [movie for movie in total_movies if movie not in seen_movies]
    unate_chickens= [food for food in total_food if food not in ate_chickens]
    
    print('평점 매긴 치킨수:',len(ate_chickens), '추천대상 치킨수:',len(unate_chickens), \
          '전체 치킨수:',len(total_food))
    
    return unate_chickens

unate_chickens = get_unate_surprise(df_sus, 'sh')

평점 매긴 치킨수: 173 추천대상 치킨수: 1140 전체 치킨수: 1227

In [30]:
def recomm_chicken_by_surprise(algo, userId, unate_chickens, top_n=10):
    # 알고리즘 객체의 predict() 메서드를 평점이 없는 치킨에 반복 수행한 후 결과를 list 객체로 저장
    predictions = [algo.predict(str(userId), str(chicken_name)) for chicken_name in unate_chickens]
    
    # predictions list 객체는 surprise의 Predictions 객체를 원소로 가지고 있음.
    # [Prediction(uid='9', iid='1', est=3.69), Prediction(uid='9', iid='2', est=2.98),,,,]
    # 이를 est 값으로 정렬하기 위해서 아래의 sortkey_est 함수를 정의함.
    # sortkey_est 함수는 list 객체의 sort() 함수의 키 값으로 사용되어 정렬 수행.
    def sortkey_est(pred):
        return pred.est
    
    # sortkey_est( ) 반환값의 내림 차순으로 정렬 수행하고 top_n개의 최상위 값 추출.
    predictions.sort(key=sortkey_est, reverse=True)
    top_predictions= predictions[:top_n]
    
    # top_n으로 추출된 영화의 정보 추출. 영화 아이디, 추천 예상 평점, 제목 추출
    # top_movie_ids = [ int(pred.iid) for pred in top_predictions]
    # top_movie_rating = [ pred.est for pred in top_predictions]
    # top_movie_titles = movies[movies.movieId.isin(top_movie_ids)]['title']
    # top_movie_preds = [ (id, title, rating) for id, title, rating in zip(top_movie_ids, top_movie_titles, top_movie_rating)]
    
    return top_predictions

unate_chickens = get_unate_surprise(df_sus, 'ck')
top_chicken_preds = recomm_chicken_by_surprise(algo, 'ck', unate_chickens, top_n=10)
print('##### Top-10 추천 영화 리스트 #####')

for top_rem in top_chicken_preds:
    #print(top_movie[1], ":", top_movie[2])
    print(top_rem[1])

평점 매긴 치킨수: 35 추천대상 치킨수: 1197 전체 치킨수: 1227
##### Top-10 추천 영화 리스트 #####
눈꽃치즈치킨（무＋소스＋콜라）
반반치킨（후라이드반＋간장반）（무＋소스＋콜라）
세트4（후라이드＋
눈꽃치즈감자
순살 핫토스치킨
내맘대로 순살 세가지맛
크리스피 반반세트
반반순살（매운맛）
THE 바삭 치파포 세트 V5
닭다리 순살만 치폴라 반.반 치킨

In [31]:
df['사용자id'].unique()

array(['st', 'yh', 'id', 'rl', 'ye', '23', 'se', 'lo', 'ad', 'es', 'cu',
       'tj', 'ch', 'ja', 'sl', 'hs', 'yu', 'fo', 'me', 'sh', 'ko', 'sw',
       'ke', 'hi', 'po', 'pi', 'dl', 'do', 'ui', 'nn', '11', 'bd', 'wo',
       'ju', 'ac', 'ss', 'kk', 'ks', 'le', 'ee', '93', 'ji', 'ni', 'ge',
       'go', 'jo', 'pa', 'oa', 'mw', 'eh', 'si', 'hu', 'qw', 'zl', 'ba',
       'kc', 'mi', 'ns', 'k0', 'ru', 'ic', 'dn', 'ma', 're', '6_', 'da',
       'am', 'mo', 'ki', 'wj', 'sj', 'eu', 'he', 'it', 'al', '21', 'az',
       'by', 'gk', 'dd', 'hy', 'ti', 'sa', 'cx', 'qk', 'in', 'lk', 'ar',
       'yo', 'km', 'ha', 'f3', 'ng', 'so', 'ya', 'an', 'ky', 'su', 'p5',
       'mk', 'ps', '84', 'gu', 'my', 'li', 'fb', 'la', 'tw', 'om', 'hj',
       'mm', 'sd', 'xe', 'bj', 'ck', '04', 'kh', 'vi', '18', 'dh', 'cj',
       'as', '37', 'db', 'yb', 'iz', 'gn', '10', 'hn', 'jf', 'bl', 'ls',
       'sk', 'ct', 'be', 'br', 'xo', 'hh', 'sy', 'kj', 'ku', 'ap', 'nk',
       'zx', 'tk', 'yn', 'ly', 'zo', 'wk', 'r2', 'wh', 'bu', 'gi', 'oh',
       'tr', 'sm', 'ok', 'a7', 'ny', 'c6', '01', 'q_', 'je', 'ry', 'mu',
       'jj', 'un', 'di', 'eg', 'rw', 'jk', 'pj', 'oj', 'ta', 'jy', 'ty',
       'de', 'fu', 'wi', '72', '6i', 'cb', '3q', 'j1', 'gh', 'sc', 'pw',
       'tt', 'rn', 'ne', '32', 'qo', 'ws', 'pl', 'bb', 'qz', 'cc', 'va',
       '19', 'wl', 'jd', 'zt', 'wn', 'yj', 'aj', 'vo', 'ka', 'll', 'dg',
       'to', 'cs', 'ot', 'v2', 'iv', 'on', 'jh', 'kd', 'mr', 'tf', 'lj',
       'ek', 'dm', 'tn', 'co', 'na', 'jm', 'ci', 'dk', 'tp', 'ho', 'k1',
       'o_', 'sb', 'ak', 'ix', 'is', 'yy', 'ev', 'tb', 'qc', 'lu', 'wz',
       '1m', 'hb', 'ql', 'ro', 'aw', 'pr', 'ca', 'wu', 'qu', 'bo', 'th',
       'w6', 'el', 'qm', 'sg', 'ex', 'no', 'yc', '98', '20', 'pe', 'rk',
       'hk', 'wp', '40', 'dr', 'ep', 'gw', 'lh', 'ms', 'gr', 'pk', 'ai',
       'du', '9j', 'bs', 'nl', 'wa', 'ww', 'p2', 'yk', '33', '52', '15',
       'hq', 'jb', 'kt', 'uo', 'dp', 'py', 'dy', '75', 'cw', 'pf', 'gp',
       'bg', 'zu', 'kw', '25', 'kb', 'vb', 'cy', 's1', '91', 'ax', 'ri',
       'a9', 'js', 'vk', '24', 'k.', '12', 'wf', 'ii', 'au', 'za', 'il',
       'gm', '14', 'fr', '50', 'yg', 'xi', 'yi', 'fh', 'nm', 'hv', 'sz',
       '8_', 'pp', '9v', '51', 'q1', 'fn', 'eo', 'sp', 'tm', 'mj', 'bi',
       'zn', 's.', 'zz', 'pc', 'a0', 'ln', 'rh', 'dq', 'im', 'kz', 'lv',
       '49', 'ze', 'ga', 'lm', 'ph', '-e', 'm9', 'ym', 'yw', 's-', 'xs',
       'ol', 'bk', 'nd', '74', 'ik', '90', '59', 'cv', 'ys', 'cm', 'yx',
       'wq', 'vj', '3g', 'cf', 'x8', '79', 'jc', 'jp', 'lz', 'bw', 'qn',
       'mz', 'qa', 'tl', 'os', 'jw', 'rt', 'ff', '6f', 'ab', 'ih', 'ld',
       've', 'pd', '41', 'tg', 'ce', 'uc', 'uf', 'xy', 'zi', 'ia', 'ay',
       'pu', '80', 'sr', 'zh', 'or', '89', 'te', 'lp', 'cr', 'at', '03',
       'ur', 'aa', 'ah', 'n5', 'qj', '05', '26', 'fa', 'cp', 'ec', 'jl',
       'kf', 'we', 'cq', 'oy', '82', 'em', 'y5', 'gf', 'i6', 'op', 'y0',
       '57', '06', 'gt', 'gg', 'jr', 'af', 'd_', 'gd', 'vn', '00', 'q2',
       'gj', '1s', 'cl', 'ej', '8c', 'uk', 'm.', '1l', 'ds', '66', 'kp',
       '29', 'bh', 'tc', 'xh', 'dw', '1b', 'hm', 'pz', 'hp', 's2', 'xl',
       'mv', 'tu', 'uw', 'ht', 'qh', 'ow', 'tv', 'jt', 'rb', 'vz', 'fl',
       'dj', 'hc', 'rd', 'gy', '99', 'mn', '5s', 'ra', 'xk', 'mb', '34',
       'fi', 'pv', 's9', 'wc', 'hd', 'lc', 'c9', 'rj', 'bn', 'n2', 'h_',
       'zp', 'Ch', 'kr', '46', 'xb', 'up', '43', 'j6', 'jx', 'kn', 'od',
       'en', '69', 'ob', 'av', 'q4', 'ir', '78', 'q8', '22', 'rm', '54',
       '30', 'ts', 'xn', '27', 'l_', 'gl', '77', 'ea', 'mt', 'pg', 'gs',
       'oo', 'pb', '8r', 'vl', 'bv', 'wr', 'ul', 'zk', 'xu', '7x', '94',
       '2u', 'ed', 'hl', 'cg', 'lt', 'bc', 'a-', 'n_', 'hw', 'us', 'ag',
       'j3', '2n', 'ip', '56', 'zy', 'jg', '55', 'ae', 'l6', 'k7', '3a',
       '97', 'hf', 'zj', 'wb', '02', 'iw', 't2', 'kl', 'ov', 'zv', '76',
       '16', 'yq', '39', 'wd', 'pn', 'wm', 'y6', 'fx', 'vh', 'er', '2m',
       'bm', 'eb', 'h1', '0o', 'yv', 'sn', 'a3', '95', 'hg', 'pt', '09',
       'fz', 'nt', '67', 'r6', 'vp', 'yz', 'nz', '8u', 'uj', 'mf', 'vc',
       '_-', 'e5', 'j8', 'qi', 'm_', 'f8', '83', 'ij', 'ei', 'vm', 'mg',
       'iy', '1q', 'j2', 'z1', 'fc', 'ml', '87', 'dx', 't4', '5_', 'zb',
       'kv', 'gx', 'fk', 'e_', 's3', 'mh', 'c1', '1w', '0e', '5z', 'yd',
       'm2', 'qp', 'd7', 'm5', 'lg', 'qt', 'm4', 'ao', '2w', 'mc', 'c2',
       'vu', 'nu', 'wv', '70', 'b2', 'bz', '85', '6t', 'nj', 'n9', 'vv',
       'ef', 'uh', '0m', '13', 'yl', 'y7', 'yt', 'gc', 'ig', 'kg', 'px',
       '2p', 'rv', 'm8', 'lw', '9l', '3w', 'df', '31', '88', '28', 'nh',
       'wy', '17', '9d', 'xx', 's0', 'j.', 'dv', 'o3', 'n-', 'ew', 'ey',
       'cd', 't5', '60', 'cn', 'wx', 's7', '5t', 'wg', 'k9', '-_', 't7',
       'nb', 'fe', '65', '0l', 'uu', 'k4', 'uq', 'fy', '86', '42', 'e1',
       'aq', 'y3', '96', 'h9', 'fp', '36', 'zq', 'jn', 'qq', '9h', 'hx',
       'p_', 'zm', 'dt', '35', '5j', 'oz', 'Tj', 'vg', 'i_', 'rp', 'rr',
       'mp', 'ib', '7f', 'l-', 'b6', 'nc', 'x4', '5q', '5n', '-s', 'v9',
       'hr', '5h', 'io', 'lb', 'p9', '0_', 'rg', '2_', 'i3', 'ou', 'x3',
       'xv', '4j', '2h', 'xm', 'wt', 'um', '08', 'k2', 'j0', 'og', 'xp',
       'yf', 'u8', 'n0', '53', 'zd', 'vy', 'l8', '1d', '3z', '6j', 's_',
       'y-', 'qb', '2s', 'b_', 'of', 'g8', 'xf', 'gb', '6o', '5b', 'i1',
       '2d', 'a2', 'uy', 'eq'], dtype=object)